# -*- coding: utf-8 -*-
"""combined_response_feature.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1122V0tlh4SkUYfPa2AxENTWwQYdRbzX8
"""

# -*- coding: utf-8 -*-
"""
File3_Combined_Response_Feature.py

KẾT HỢP Response-KD (Word-KD) + Feature-KD (FitNets), so với No-KD baseline.
Teacher: BLIP-large (fine-tune decoder trên Fashion200k trước khi distill).
Student: BLIP-base.

Công thức loss (KHÔNG dùng combo lồi (1-a)*x+a*y vì có 2 loss phụ trở lên,
mỗi loss có trọng số ĐỘC LẬP, tổng không cần bằng 1):

    L = L_gt + LAMBDA_RESPONSE * L_response_KD + LAMBDA_FEATURE * L_feature_KD

  - L_gt            : cross-entropy với ground-truth caption (giống mọi cấu hình khác)
  - L_response_KD   : KL-divergence giữa phân phối token Student/Teacher (Word-KD)
  - L_feature_KD    : MSE giữa pooled feature ảnh Student (qua Adapter) và Teacher (FitNets)

⚠️ 3 giá trị loss này được in RIÊNG mỗi epoch — vì các loss có magnitude khác
nhau (vd loss_feature có thể nhỏ hơn loss_response nhiều lần), nếu 1 loss lớn
hơn hẳn sẽ "át" gradient của loss còn lại. Theo dõi log để tinh chỉnh
LAMBDA_RESPONSE / LAMBDA_FEATURE cho cân bằng, không có công thức cố định.

Chạy ĐỘC LẬP trong 1 session Kaggle/Colab riêng — không phụ thuộc File1/File2.
Data (train/val/test) được tải từ 3 file .zip đã chuẩn bị sẵn bởi
prepare_fashion200k_splits.py (sửa 2 URL bên dưới trước khi chạy).
"""

# =====================================================================
# PHẦN 0 — CÀI ĐẶT & IMPORT
# =====================================================================
import os
os.environ.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")

!pip install -q pycocoevalcap rouge_score
!pip install -q datasets transformers accelerate Pillow requests nltk evaluate torch torchvision

import gc, json, random, zipfile, urllib.request
import torch
import torch.nn as nn
import torch.nn.functional as F
from PIL import Image
from transformers import (
    BlipProcessor, BlipForConditionalGeneration, get_linear_schedule_with_warmup
)
from torch.optim import AdamW
import evaluate
from pycocoevalcap.cider.cider import Cider
import pandas as pd

RANDOM_SEED = 42
random.seed(RANDOM_SEED)
torch.manual_seed(RANDOM_SEED)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"CUDA available: {torch.cuda.is_available()}")

SHARED_PROCESSOR = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
PAD_ID = SHARED_PROCESSOR.tokenizer.pad_token_id

NUM_EPOCHS   = 10
BATCH_SIZE   = 4
BATCH_SIZE_COMBO = max(1, BATCH_SIZE // 2)  # combo nặng nhất (response + feature cùng lúc) -> batch nhỏ hơn
BATCH_SIZE_TEACHER_FT = max(1, BATCH_SIZE // 2)
LR           = 1e-5
MAX_LEN      = 64
WARMUP_RATIO = 0.1
TEMPERATURE  = 4.0
LAMBDA_RESPONSE = 1.0   # bắt đầu bằng 1.0, tinh chỉnh dựa trên log 3 loss mỗi epoch
LAMBDA_FEATURE  = 1.0
TEACHER_FT_EPOCHS = 5
TEACHER_FT_LR = 5e-6
USE_AMP = True

results = {}


def make_labels(input_ids: torch.Tensor) -> torch.Tensor:
    labels = input_ids.clone()
    labels[labels == PAD_ID] = -100
    labels[:, 0] = -100
    return labels


def free_gpu(*names):
    """Xóa biến TOÀN CỤC theo TÊN (chuỗi) rồi dọn rác + cache CUDA.
    Phải truyền tên dạng chuỗi (vd free_gpu('model_x', 'optimizer_x')), KHÔNG
    truyền thẳng object — truyền object chỉ xóa được tham chiếu cục bộ bên
    trong hàm, biến toàn cục ngoài vẫn giữ nguyên -> không giải phóng được
    bộ nhớ GPU thật sự."""
    g = globals()
    for name in names:
        if name in g:
            del g[name]
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        torch.cuda.synchronize()
        print(f"   [dọn bộ nhớ] Đang dùng: {torch.cuda.memory_allocated()/1e9:.2f} GB "
              f"| Đã cấp phát (reserved): {torch.cuda.memory_reserved()/1e9:.2f} GB")

import shutil

# Xóa các file zip lỗi và thư mục giải nén cũ để tải lại sạch sẽ
files_to_remove = ['train.zip', 'val.zip']
dirs_to_remove = ['data_train', 'data_val']

for f in files_to_remove:
    if os.path.exists(f):
        os.remove(f)
        print(f"Đã xóa file lỗi: {f}")

for d in dirs_to_remove:
    if os.path.exists(d):
        shutil.rmtree(d)
        print(f"Đã xóa thư mục cũ: {d}")

print("--- Sẵn sàng để chạy lại ô tải dữ liệu bên trên! ---")

# =====================================================================
# PHẦN 1 — TẢI DATA
# =====================================================================
TRAIN_ZIP_URL = "https://github.com/Q-Anh2610/demo_Lab/raw/main/Tuan_4/dataset/fashion200k_train.zip"
VAL_ZIP_URL   = "https://github.com/Q-Anh2610/demo_Lab/raw/main/Tuan_4/dataset/fashion200k_val.zip"


def load_split_from_zip(zip_path_or_url, split_name):
    target_dir = f"data_{split_name}"
    if zip_path_or_url.startswith("http"):
        local_zip = f"{split_name}.zip"
        if not os.path.exists(local_zip):
            print(f"Đang tải {split_name} từ {zip_path_or_url} ...")
            urllib.request.urlretrieve(zip_path_or_url, local_zip)
    else:
        local_zip = zip_path_or_url

    if not os.path.exists(target_dir):
        with zipfile.ZipFile(local_zip, "r") as zf:
            zf.extractall(target_dir)

    with open(os.path.join(target_dir, "metadata.json"), encoding="utf-8") as f:
        metadata = json.load(f)
    for item in metadata:
        item["image_path"] = os.path.join(target_dir, "images", item["image_file"])
    return metadata


fashion_train = load_split_from_zip(TRAIN_ZIP_URL, "train")
fashion_val   = load_split_from_zip(VAL_ZIP_URL, "val")
print(f"Train: {len(fashion_train)} | Val: {len(fashion_val)}")

steps_per_epoch = max(1, len(fashion_train) // BATCH_SIZE)
total_steps  = steps_per_epoch * NUM_EPOCHS
warmup_steps = int(total_steps * WARMUP_RATIO)

# =====================================================================
# PHẦN 2 — HÀM ĐÁNH GIÁ
# =====================================================================
bleu = evaluate.load("bleu")
rouge = evaluate.load("rouge")
cider_scorer = Cider()


def evaluate_model(model, eval_metadata, is_teacher=False, max_samples=None):
    model.eval()
    predictions, references = [], []
    cider_refs, cider_preds = {}, {}
    samples_to_eval = eval_metadata[:max_samples] if max_samples else eval_metadata
    print(f"Đang đánh giá trên {len(samples_to_eval)} mẫu...")

    with torch.no_grad():
        for i, item in enumerate(samples_to_eval):
            img = Image.open(item["image_path"]).convert("RGB")
            inputs = SHARED_PROCESSOR(images=img, return_tensors="pt").to(DEVICE)
            if is_teacher:
                inputs["pixel_values"] = inputs["pixel_values"].half()
                generated_ids = model.generate(**inputs, max_new_tokens=40)
            else:
                with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=USE_AMP and DEVICE == "cuda"):
                    generated_ids = model.generate(**inputs, max_new_tokens=40)
            pred = SHARED_PROCESSOR.decode(generated_ids[0], skip_special_tokens=True)
            predictions.append(pred)
            references.append([item["caption"]])
            cider_preds[i] = [pred]
            cider_refs[i] = [item["caption"]]

    bleu_score  = bleu.compute(predictions=predictions, references=references)["bleu"]
    rouge_score = rouge.compute(predictions=predictions, references=references)["rougeL"]
    (cider_score, _) = cider_scorer.compute_score(cider_refs, cider_preds)
    return bleu_score, rouge_score, cider_score

# =====================================================================
# PHẦN 3 — TEACHER (BLIP-large): zero-shot -> fine-tune decoder -> đóng băng
# =====================================================================
teacher_model = BlipForConditionalGeneration.from_pretrained(
    "Salesforce/blip-image-captioning-large", torch_dtype=torch.float16
).to(DEVICE).eval()
for p in teacher_model.parameters():
    p.requires_grad = False

print("--- Đánh giá Teacher (zero-shot) trên VAL SET ---")
teach_zs_bleu, teach_zs_rouge, teach_zs_cider = evaluate_model(teacher_model, fashion_val, is_teacher=True)
results["Teacher (zero-shot)"] = (teach_zs_bleu, teach_zs_rouge, teach_zs_cider)
print(f"Teacher (zero-shot): BLEU={teach_zs_bleu:.4f} ROUGE-L={teach_zs_rouge:.4f} CIDEr={teach_zs_cider:.4f}")

for p in teacher_model.parameters():
    p.requires_grad = True
for p in teacher_model.vision_model.parameters():
    p.requires_grad = False
trainable_teacher_params = [p for p in teacher_model.parameters() if p.requires_grad]
print(f"Số tham số Teacher sẽ fine-tune: {sum(p.numel() for p in trainable_teacher_params)/1e6:.1f}M")

for name, module in teacher_model.named_children():
    if name != "vision_model":
        module.float()

try:
    teacher_model.gradient_checkpointing_enable()
except Exception as e:
    print(f"Không bật được gradient checkpointing: {e}")

optimizer_teacher = AdamW(trainable_teacher_params, lr=TEACHER_FT_LR, weight_decay=0.01)
t_steps = max(1, len(fashion_train) // BATCH_SIZE_TEACHER_FT) * TEACHER_FT_EPOCHS
scheduler_teacher = get_linear_schedule_with_warmup(
    optimizer_teacher, num_warmup_steps=int(t_steps * WARMUP_RATIO), num_training_steps=t_steps
)
scaler_teacher = torch.cuda.amp.GradScaler(enabled=USE_AMP and DEVICE == "cuda")

print(f"Fine-tune Teacher: {TEACHER_FT_EPOCHS} epochs | batch_size={BATCH_SIZE_TEACHER_FT}")
teacher_model.train()
for epoch in range(TEACHER_FT_EPOCHS):
    epoch_losses = []
    for start in range(0, len(fashion_train), BATCH_SIZE_TEACHER_FT):
        batch = fashion_train[start:start + BATCH_SIZE_TEACHER_FT]
        if not batch:
            continue
        pil_imgs = [Image.open(b["image_path"]).convert("RGB") for b in batch]
        gt_caps  = [b["caption"] for b in batch]
        gt_enc = SHARED_PROCESSOR(images=pil_imgs, text=gt_caps, return_tensors="pt",
                                   padding="max_length", max_length=MAX_LEN, truncation=True).to(DEVICE)
        gt_labels = make_labels(gt_enc["input_ids"])

        optimizer_teacher.zero_grad()
        with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=USE_AMP and DEVICE == "cuda"):
            out = teacher_model(pixel_values=gt_enc["pixel_values"], input_ids=gt_enc["input_ids"],
                                 attention_mask=gt_enc["attention_mask"], labels=gt_labels)
            loss = out.loss
        scaler_teacher.scale(loss).backward()
        scaler_teacher.unscale_(optimizer_teacher)
        torch.nn.utils.clip_grad_norm_(trainable_teacher_params, 1.0)
        scaler_teacher.step(optimizer_teacher)
        scaler_teacher.update()
        scheduler_teacher.step()
        epoch_losses.append(loss.item())
    print(f"[Teacher FT] Epoch {epoch+1}/{TEACHER_FT_EPOCHS} | loss={sum(epoch_losses)/len(epoch_losses):.4f}")

try:
    teacher_model.gradient_checkpointing_disable()
except Exception:
    pass
teacher_model = teacher_model.half().eval()
for p in teacher_model.parameters():
    p.requires_grad = False

free_gpu('optimizer_teacher', 'scheduler_teacher', 'scaler_teacher')

print("--- Đánh giá Teacher (fine-tuned) trên VAL SET ---")
teach_ft_bleu, teach_ft_rouge, teach_ft_cider = evaluate_model(teacher_model, fashion_val, is_teacher=True)
results["Teacher (fine-tuned)"] = (teach_ft_bleu, teach_ft_rouge, teach_ft_cider)
print(f"Teacher (fine-tuned): BLEU={teach_ft_bleu:.4f} ROUGE-L={teach_ft_rouge:.4f} CIDEr={teach_ft_cider:.4f}")

# =====================================================================
# PHẦN 4 — NO-KD BASELINE
# =====================================================================
student_model_nokd = BlipForConditionalGeneration.from_pretrained(
    "Salesforce/blip-image-captioning-base"
).to(DEVICE)
optimizer_nokd = AdamW(student_model_nokd.parameters(), lr=LR, weight_decay=0.01)
scheduler_nokd = get_linear_schedule_with_warmup(
    optimizer_nokd, num_warmup_steps=warmup_steps, num_training_steps=total_steps
)
scaler_nokd = torch.cuda.amp.GradScaler(enabled=USE_AMP and DEVICE == "cuda")

print("Training No-KD baseline...")
for epoch in range(NUM_EPOCHS):
    student_model_nokd.train()
    epoch_losses = []
    for start in range(0, len(fashion_train), BATCH_SIZE):
        batch = fashion_train[start:start + BATCH_SIZE]
        if not batch:
            continue
        pil_imgs = [Image.open(b["image_path"]).convert("RGB") for b in batch]
        gt_caps  = [b["caption"] for b in batch]
        gt_enc = SHARED_PROCESSOR(images=pil_imgs, text=gt_caps, return_tensors="pt",
                                   padding="max_length", max_length=MAX_LEN, truncation=True).to(DEVICE)
        gt_labels = make_labels(gt_enc["input_ids"])

        optimizer_nokd.zero_grad()
        with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=USE_AMP and DEVICE == "cuda"):
            out = student_model_nokd(pixel_values=gt_enc["pixel_values"], input_ids=gt_enc["input_ids"],
                                      attention_mask=gt_enc["attention_mask"], labels=gt_labels)
            loss = out.loss
        scaler_nokd.scale(loss).backward()
        scaler_nokd.unscale_(optimizer_nokd)
        torch.nn.utils.clip_grad_norm_(student_model_nokd.parameters(), 1.0)
        scaler_nokd.step(optimizer_nokd)
        scaler_nokd.update()
        scheduler_nokd.step()
        epoch_losses.append(loss.item())
    print(f"[No-KD] Epoch {epoch+1}/{NUM_EPOCHS} | loss={sum(epoch_losses)/len(epoch_losses):.4f}")

print("--- Đánh giá No-KD baseline trên VAL SET ---")
nokd_bleu, nokd_rouge, nokd_cider = evaluate_model(student_model_nokd, fashion_val)
results["No-KD (baseline)"] = (nokd_bleu, nokd_rouge, nokd_cider)
print(f"No-KD: BLEU={nokd_bleu:.4f} ROUGE-L={nokd_rouge:.4f} CIDEr={nokd_cider:.4f}")

free_gpu('student_model_nokd', 'optimizer_nokd', 'scheduler_nokd', 'scaler_nokd')

# =====================================================================
# PHẦN 5 — KẾT HỢP: RESPONSE-KD (Word-KD) + FEATURE-KD (FitNets)
# =====================================================================
def compute_word_kd_loss(student_logits, teacher_logits, pad_mask, T=TEMPERATURE):
    student_log_probs = F.log_softmax(student_logits.float() / T, dim=-1)
    teacher_probs = F.softmax(teacher_logits.float() / T, dim=-1)
    kd_per_token = F.kl_div(student_log_probs, teacher_probs, reduction="none").sum(dim=-1)
    kd_per_token = kd_per_token * pad_mask
    return (kd_per_token.sum() / pad_mask.sum().clamp(min=1)) * (T ** 2)


def get_pooled_image_feature(model, pixel_values):
    vision_out = model.vision_model(pixel_values=pixel_values)
    return vision_out.pooler_output


student_model_combo = BlipForConditionalGeneration.from_pretrained(
    "Salesforce/blip-image-captioning-base"
).to(DEVICE)
teacher_hidden = teacher_model.vision_model.config.hidden_size
student_hidden = student_model_combo.vision_model.config.hidden_size
adapter_combo = nn.Linear(student_hidden, teacher_hidden).to(DEVICE)

optimizer_combo = AdamW(
    list(student_model_combo.parameters()) + list(adapter_combo.parameters()),
    lr=LR, weight_decay=0.01
)
combo_steps = max(1, len(fashion_train) // BATCH_SIZE_COMBO) * NUM_EPOCHS
scheduler_combo = get_linear_schedule_with_warmup(
    optimizer_combo, num_warmup_steps=int(combo_steps * WARMUP_RATIO), num_training_steps=combo_steps
)
scaler_combo = torch.cuda.amp.GradScaler(enabled=USE_AMP and DEVICE == "cuda")

print(f"Training Combined Response+Feature KD (batch_size={BATCH_SIZE_COMBO})...")
for epoch in range(NUM_EPOCHS):
    student_model_combo.train(); adapter_combo.train()
    epoch_losses, epoch_gt, epoch_resp, epoch_feat = [], [], [], []
    for start in range(0, len(fashion_train), BATCH_SIZE_COMBO):
        batch = fashion_train[start:start + BATCH_SIZE_COMBO]
        if not batch:
            continue
        pil_imgs = [Image.open(b["image_path"]).convert("RGB") for b in batch]
        gt_caps  = [b["caption"] for b in batch]
        gt_enc = SHARED_PROCESSOR(images=pil_imgs, text=gt_caps, return_tensors="pt",
                                   padding="max_length", max_length=MAX_LEN, truncation=True).to(DEVICE)
        gt_labels = make_labels(gt_enc["input_ids"])
        pad_mask = (gt_labels != -100).float()

        # Teacher: lấy CẢ logits (response) VÀ pooled feature (feature) trong no_grad
        with torch.no_grad():
            teacher_out = teacher_model(pixel_values=gt_enc["pixel_values"].half(),
                                         input_ids=gt_enc["input_ids"], attention_mask=gt_enc["attention_mask"])
            teacher_logits = teacher_out.logits
            teacher_feat = get_pooled_image_feature(teacher_model, gt_enc["pixel_values"].half()).float()

        optimizer_combo.zero_grad()
        with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=USE_AMP and DEVICE == "cuda"):
            student_feat = get_pooled_image_feature(student_model_combo, gt_enc["pixel_values"])
            adapted_feat = adapter_combo(student_feat)
            loss_feature = F.mse_loss(adapted_feat.float(), teacher_feat)

            student_out = student_model_combo(pixel_values=gt_enc["pixel_values"], input_ids=gt_enc["input_ids"],
                                               attention_mask=gt_enc["attention_mask"], labels=gt_labels)
            loss_gt = student_out.loss
            loss_response = compute_word_kd_loss(student_out.logits, teacher_logits, pad_mask)

            loss = loss_gt + LAMBDA_RESPONSE * loss_response + LAMBDA_FEATURE * loss_feature

        scaler_combo.scale(loss).backward()
        scaler_combo.unscale_(optimizer_combo)
        torch.nn.utils.clip_grad_norm_(
            list(student_model_combo.parameters()) + list(adapter_combo.parameters()), 1.0
        )
        scaler_combo.step(optimizer_combo)
        scaler_combo.update()
        scheduler_combo.step()

        epoch_losses.append(loss.item())
        epoch_gt.append(loss_gt.item())
        epoch_resp.append(loss_response.item())
        epoch_feat.append(loss_feature.item())

    print(f"[Combo] Epoch {epoch+1}/{NUM_EPOCHS} | total={sum(epoch_losses)/len(epoch_losses):.4f} "
          f"| gt={sum(epoch_gt)/len(epoch_gt):.4f} "
          f"| response={sum(epoch_resp)/len(epoch_resp):.4f} "
          f"| feature={sum(epoch_feat)/len(epoch_feat):.4f}")

print("--- Đánh giá Combined KD trên VAL SET ---")
combo_bleu, combo_rouge, combo_cider = evaluate_model(student_model_combo, fashion_val)
results["Combined Response+Feature (Student)"] = (combo_bleu, combo_rouge, combo_cider)
print(f"Combined: BLEU={combo_bleu:.4f} ROUGE-L={combo_rouge:.4f} CIDEr={combo_cider:.4f}")

free_gpu('student_model_combo', 'adapter_combo', 'optimizer_combo', 'scheduler_combo', 'scaler_combo')

# =====================================================================
# PHẦN 6 — BẢNG SO SÁNH
# =====================================================================
col_order = ["Teacher (zero-shot)", "Teacher (fine-tuned)", "No-KD (baseline)",
             "Combined Response+Feature (Student)"]
data = {"Metric": ["BLEU", "ROUGE-L", "CIDEr"]}
for col in col_order:
    b, r, c = results[col]
    data[col] = [b, r, c]
df_results = pd.DataFrame(data).round(4)
print("\nBẢNG KẾT QUẢ FILE 3 — KẾT HỢP RESPONSE + FEATURE KD (VAL SET)")
display(df_results)

import matplotlib.pyplot as plt
import numpy as np
metrics = ['BLEU', 'ROUGE', 'CIDEr']
vals = [list(results[c]) for c in col_order]
colors = ['#999999', '#555555', '#B4B2A9', '#C44E52']
x = np.arange(len(metrics)); width = 0.18
fig, ax = plt.subplots(figsize=(11, 6))
for i, (v, c, lbl) in enumerate(zip(vals, colors, col_order)):
    ax.bar(x + (i - 1.5) * width, v, width, label=lbl, color=c)
ax.set_ylabel('Scores'); ax.set_xticks(x); ax.set_xticklabels(metrics)
ax.set_title('File 3 — Combined Response+Feature KD vs No-KD (Fashion200k, val set)')
ax.legend(); fig.tight_layout(); plt.show()

with open("results_file3.json", "w") as f:
    json.dump({k: list(v) for k, v in results.items()}, f, indent=2)
print("Đã lưu results_file3.json")

print("\nGợi ý: sau khi chạy xong cả 3 file, có thể gộp results_file1.json,")
print("results_file2.json, results_file3.json (đều có chung Teacher/No-KD vì")
print("cùng seed + data) thành 1 bảng tổng hợp duy nhất cho báo cáo.")

import matplotlib.pyplot as plt
import random

def visualize_samples(eval_metadata, models_dict, num_samples=5):
    indices = random.sample(range(len(eval_metadata)), num_samples)
    fig, axes = plt.subplots(num_samples, 1, figsize=(15, 8 * num_samples))

    for i, idx in enumerate(indices):
        item = eval_metadata[idx]
        img = Image.open(item['image_path']).convert('RGB')

        axes[i].imshow(img)
        axes[i].axis('off')

        texts = f"**Ground Truth:** {item['caption']}\n"

        for label, model in models_dict.items():
            if model is None:
                texts += f"**{label}:** (Model not loaded/deleted)\n"
                continue

            model.eval()
            inputs = SHARED_PROCESSOR(images=img, return_tensors='pt').to(DEVICE)
            with torch.no_grad():
                # Xử lý trường hợp Teacher dùng float16
                if 'Teacher' in label:
                    inputs['pixel_values'] = inputs['pixel_values'].half()

                generated_ids = model.generate(**inputs, max_new_tokens=40)
                pred = SHARED_PROCESSOR.decode(generated_ids[0], skip_special_tokens=True)
                texts += f"**{label}:** {pred}\n"

        axes[i].set_title(texts, loc='left', fontsize=11, wrap=True)

    plt.tight_layout()
    plt.show()

# --- TẢI LẠI MÔ HÌNH NẾU ĐÃ BỊ XÓA ---
print("Đang kiểm tra và tải lại các mô hình để hiển thị...")

if 'student_model_nokd' not in globals():
    student_model_nokd = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base").to(DEVICE)

if 'student_model_combo' not in globals():
    # Lưu ý: Ở đây ta load base model, nếu bạn có lưu checkpoint thì nên load từ checkpoint.
    # Nếu không, code này sẽ hiện kết quả của model base (pre-trained).
    student_model_combo = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base").to(DEVICE)

models_to_show = {
    "Teacher (FT)": teacher_model if 'teacher_model' in globals() else None,
    "No-KD Baseline": student_model_nokd,
    "Combined KD": student_model_combo
}

visualize_samples(fashion_val, models_to_show, num_samples=5)