# -*- coding: utf-8 -*-
"""responsekd_seqword.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13PeWy0so3gqOMGiXsDUENV_qOkXrRHoV
"""

# -*- coding: utf-8 -*-
"""
File1_ResponseKD_SeqWord.py

RESPONSE-BASED KD: Seq-KD + Word-KD, so với No-KD baseline.
Teacher: BLIP-large (fine-tune decoder trên Fashion200k trước khi distill).
Student: BLIP-base.

Chạy ĐỘC LẬP trong 1 session Kaggle/Colab riêng — không phụ thuộc file nào
khác. Data (train/val/test) được tải từ 3 file .zip đã chuẩn bị sẵn bởi
prepare_fashion200k_splits.py (sửa 3 URL bên dưới trước khi chạy).
"""

# =====================================================================
# PHẦN 0 — CÀI ĐẶT & IMPORT
# =====================================================================
import os
os.environ.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")

!pip install -q pycocoevalcap rouge_score
!pip install -q datasets transformers accelerate Pillow requests nltk evaluate torch torchvision

import gc, json, random, zipfile, urllib.request
import torch
import torch.nn as nn
import torch.nn.functional as F
from PIL import Image
from transformers import (
    BlipProcessor, BlipForConditionalGeneration, get_linear_schedule_with_warmup
)
from torch.optim import AdamW
import evaluate
from pycocoevalcap.cider.cider import Cider
import pandas as pd

RANDOM_SEED = 42
random.seed(RANDOM_SEED)
torch.manual_seed(RANDOM_SEED)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"CUDA available: {torch.cuda.is_available()}")

SHARED_PROCESSOR = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
PAD_ID = SHARED_PROCESSOR.tokenizer.pad_token_id

NUM_EPOCHS   = 10
BATCH_SIZE   = 4
BATCH_SIZE_TEACHER_FT = max(1, BATCH_SIZE // 2)
LR           = 1e-5
MAX_LEN      = 64
WARMUP_RATIO = 0.1
ALPHA_SEQ    = 0.4
ALPHA_WORD   = 0.7
TEMPERATURE  = 4.0
TEACHER_FT_EPOCHS = 5
TEACHER_FT_LR = 5e-6
USE_AMP = True

results = {}


def make_labels(input_ids: torch.Tensor) -> torch.Tensor:
    labels = input_ids.clone()
    labels[labels == PAD_ID] = -100
    labels[:, 0] = -100
    return labels


def free_gpu(*names):
    """Xóa biến TOÀN CỤC theo TÊN (chuỗi) rồi dọn rác + cache CUDA.
    Phải truyền tên dạng chuỗi (vd free_gpu('model_x', 'optimizer_x')), KHÔNG
    truyền thẳng object — truyền object chỉ xóa được tham chiếu cục bộ bên
    trong hàm, biến toàn cục ngoài vẫn giữ nguyên -> không giải phóng được
    bộ nhớ GPU thật sự."""
    g = globals()
    for name in names:
        if name in g:
            del g[name]
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        torch.cuda.synchronize()
        print(f"   [dọn bộ nhớ] Đang dùng: {torch.cuda.memory_allocated()/1e9:.2f} GB "
              f"| Đã cấp phát (reserved): {torch.cuda.memory_reserved()/1e9:.2f} GB")

import shutil

# Xóa các file zip lỗi và thư mục giải nén cũ để tải lại sạch sẽ
files_to_remove = ['train.zip', 'val.zip']
dirs_to_remove = ['data_train', 'data_val']

for f in files_to_remove:
    if os.path.exists(f):
        os.remove(f)
        print(f"Đã xóa file lỗi: {f}")

for d in dirs_to_remove:
    if os.path.exists(d):
        shutil.rmtree(d)
        print(f"Đã xóa thư mục cũ: {d}")

print("--- Sẵn sàng để chạy lại ô tải dữ liệu bên trên! ---")

# =====================================================================
# PHẦN 1 — TẢI DATA (từ 3 file .zip đã chuẩn bị sẵn — xem prepare_fashion200k_splits.py)
# =====================================================================
# ⚠️ SỬA 2 URL NÀY trước khi chạy (raw GitHub link, hoặc path Kaggle Dataset local)
TRAIN_ZIP_URL = "https://github.com/Q-Anh2610/demo_Lab/raw/main/Tuan_4/dataset/fashion200k_train.zip"
VAL_ZIP_URL   = "https://github.com/Q-Anh2610/demo_Lab/raw/main/Tuan_4/dataset/fashion200k_val.zip"
# fashion_test KHÔNG cần tải ở đây — chỉ dùng 1 lần cuối kỳ


def load_split_from_zip(zip_path_or_url, split_name):
    """Tải (nếu là URL) + giải nén 1 split -> trả về list metadata với
    image_path cục bộ sẵn sàng để Image.open(). Nếu zip_path_or_url là
    đường dẫn local (vd Kaggle Dataset đã Add Input), truyền thẳng path đó."""
    target_dir = f"data_{split_name}"
    if zip_path_or_url.startswith("http"):
        local_zip = f"{split_name}.zip"
        if not os.path.exists(local_zip):
            print(f"Đang tải {split_name} từ {zip_path_or_url} ...")
            urllib.request.urlretrieve(zip_path_or_url, local_zip)
    else:
        local_zip = zip_path_or_url

    if not os.path.exists(target_dir):
        with zipfile.ZipFile(local_zip, "r") as zf:
            zf.extractall(target_dir)

    with open(os.path.join(target_dir, "metadata.json"), encoding="utf-8") as f:
        metadata = json.load(f)
    for item in metadata:
        item["image_path"] = os.path.join(target_dir, "images", item["image_file"])
    return metadata


fashion_train = load_split_from_zip(TRAIN_ZIP_URL, "train")
fashion_val   = load_split_from_zip(VAL_ZIP_URL, "val")
print(f"Train: {len(fashion_train)} | Val: {len(fashion_val)}")

steps_per_epoch = max(1, len(fashion_train) // BATCH_SIZE)
total_steps  = steps_per_epoch * NUM_EPOCHS
warmup_steps = int(total_steps * WARMUP_RATIO)

# =====================================================================
# PHẦN 2 — HÀM ĐÁNH GIÁ
# =====================================================================
bleu = evaluate.load("bleu")
rouge = evaluate.load("rouge")
cider_scorer = Cider()


def evaluate_model(model, eval_metadata, is_teacher=False, max_samples=None):
    model.eval()
    predictions, references = [], []
    cider_refs, cider_preds = {}, {}
    samples_to_eval = eval_metadata[:max_samples] if max_samples else eval_metadata
    print(f"Đang đánh giá trên {len(samples_to_eval)} mẫu...")

    with torch.no_grad():
        for i, item in enumerate(samples_to_eval):
            img = Image.open(item["image_path"]).convert("RGB")
            inputs = SHARED_PROCESSOR(images=img, return_tensors="pt").to(DEVICE)
            if is_teacher:
                inputs["pixel_values"] = inputs["pixel_values"].half()
                generated_ids = model.generate(**inputs, max_new_tokens=40)
            else:
                with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=USE_AMP and DEVICE == "cuda"):
                    generated_ids = model.generate(**inputs, max_new_tokens=40)
            pred = SHARED_PROCESSOR.decode(generated_ids[0], skip_special_tokens=True)
            predictions.append(pred)
            references.append([item["caption"]])
            cider_preds[i] = [pred]
            cider_refs[i] = [item["caption"]]

    bleu_score  = bleu.compute(predictions=predictions, references=references)["bleu"]
    rouge_score = rouge.compute(predictions=predictions, references=references)["rougeL"]
    (cider_score, _) = cider_scorer.compute_score(cider_refs, cider_preds)
    return bleu_score, rouge_score, cider_score

# =====================================================================
# PHẦN 3 — TEACHER (BLIP-large): zero-shot -> fine-tune decoder -> đóng băng
# =====================================================================
teacher_model = BlipForConditionalGeneration.from_pretrained(
    "Salesforce/blip-image-captioning-large", torch_dtype=torch.float16
).to(DEVICE).eval()
for p in teacher_model.parameters():
    p.requires_grad = False


@torch.no_grad()
def get_pseudo_labels(pil_images):
    inputs = SHARED_PROCESSOR(images=pil_images, return_tensors="pt", padding=True).to(DEVICE)
    inputs["pixel_values"] = inputs["pixel_values"].half()
    ids = teacher_model.generate(**inputs, max_new_tokens=40, num_beams=3, early_stopping=True)
    return SHARED_PROCESSOR.batch_decode(ids, skip_special_tokens=True)


print("--- Đánh giá Teacher (zero-shot) trên VAL SET ---")
teach_zs_bleu, teach_zs_rouge, teach_zs_cider = evaluate_model(teacher_model, fashion_val, is_teacher=True)
results["Teacher (zero-shot)"] = (teach_zs_bleu, teach_zs_rouge, teach_zs_cider)
print(f"Teacher (zero-shot): BLEU={teach_zs_bleu:.4f} ROUGE-L={teach_zs_rouge:.4f} CIDEr={teach_zs_cider:.4f}")

# Fine-tune CHỈ decoder + cross-attn, đóng băng vision encoder (giảm bộ nhớ +
# giảm overfit với dataset nhỏ). Xem giải thích chi tiết trong file gốc tuần 4.
for p in teacher_model.parameters():
    p.requires_grad = True
for p in teacher_model.vision_model.parameters():
    p.requires_grad = False
trainable_teacher_params = [p for p in teacher_model.parameters() if p.requires_grad]
print(f"Số tham số Teacher sẽ fine-tune: {sum(p.numel() for p in trainable_teacher_params)/1e6:.1f}M")

for name, module in teacher_model.named_children():
    if name != "vision_model":
        module.float()   # chỉ phần train mới lên fp32, vision giữ fp16

try:
    teacher_model.gradient_checkpointing_enable()
except Exception as e:
    print(f"Không bật được gradient checkpointing: {e}")

optimizer_teacher = AdamW(trainable_teacher_params, lr=TEACHER_FT_LR, weight_decay=0.01)
t_steps = max(1, len(fashion_train) // BATCH_SIZE_TEACHER_FT) * TEACHER_FT_EPOCHS
scheduler_teacher = get_linear_schedule_with_warmup(
    optimizer_teacher, num_warmup_steps=int(t_steps * WARMUP_RATIO), num_training_steps=t_steps
)
scaler_teacher = torch.cuda.amp.GradScaler(enabled=USE_AMP and DEVICE == "cuda")

print(f"Fine-tune Teacher: {TEACHER_FT_EPOCHS} epochs | batch_size={BATCH_SIZE_TEACHER_FT}")
teacher_model.train()
for epoch in range(TEACHER_FT_EPOCHS):
    epoch_losses = []
    for start in range(0, len(fashion_train), BATCH_SIZE_TEACHER_FT):
        batch = fashion_train[start:start + BATCH_SIZE_TEACHER_FT]
        if not batch:
            continue
        pil_imgs = [Image.open(b["image_path"]).convert("RGB") for b in batch]
        gt_caps  = [b["caption"] for b in batch]
        gt_enc = SHARED_PROCESSOR(images=pil_imgs, text=gt_caps, return_tensors="pt",
                                   padding="max_length", max_length=MAX_LEN, truncation=True).to(DEVICE)
        gt_labels = make_labels(gt_enc["input_ids"])

        optimizer_teacher.zero_grad()
        with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=USE_AMP and DEVICE == "cuda"):
            out = teacher_model(pixel_values=gt_enc["pixel_values"], input_ids=gt_enc["input_ids"],
                                 attention_mask=gt_enc["attention_mask"], labels=gt_labels)
            loss = out.loss
        scaler_teacher.scale(loss).backward()
        scaler_teacher.unscale_(optimizer_teacher)
        torch.nn.utils.clip_grad_norm_(trainable_teacher_params, 1.0)
        scaler_teacher.step(optimizer_teacher)
        scaler_teacher.update()
        scheduler_teacher.step()
        epoch_losses.append(loss.item())
    print(f"[Teacher FT] Epoch {epoch+1}/{TEACHER_FT_EPOCHS} | loss={sum(epoch_losses)/len(epoch_losses):.4f}")

try:
    teacher_model.gradient_checkpointing_disable()
except Exception:
    pass
teacher_model = teacher_model.half().eval()
for p in teacher_model.parameters():
    p.requires_grad = False

free_gpu('optimizer_teacher', 'scheduler_teacher', 'scaler_teacher')

print("--- Đánh giá Teacher (fine-tuned) trên VAL SET ---")
teach_ft_bleu, teach_ft_rouge, teach_ft_cider = evaluate_model(teacher_model, fashion_val, is_teacher=True)
results["Teacher (fine-tuned)"] = (teach_ft_bleu, teach_ft_rouge, teach_ft_cider)
print(f"Teacher (fine-tuned): BLEU={teach_ft_bleu:.4f} ROUGE-L={teach_ft_rouge:.4f} CIDEr={teach_ft_cider:.4f}")

# =====================================================================
# PHẦN 4 — NO-KD BASELINE
# =====================================================================
student_model_nokd = BlipForConditionalGeneration.from_pretrained(
    "Salesforce/blip-image-captioning-base"
).to(DEVICE)
optimizer_nokd = AdamW(student_model_nokd.parameters(), lr=LR, weight_decay=0.01)
scheduler_nokd = get_linear_schedule_with_warmup(
    optimizer_nokd, num_warmup_steps=warmup_steps, num_training_steps=total_steps
)
scaler_nokd = torch.cuda.amp.GradScaler(enabled=USE_AMP and DEVICE == "cuda")

print("Training No-KD baseline...")
for epoch in range(NUM_EPOCHS):
    student_model_nokd.train()
    epoch_losses = []
    for start in range(0, len(fashion_train), BATCH_SIZE):
        batch = fashion_train[start:start + BATCH_SIZE]
        if not batch:
            continue
        pil_imgs = [Image.open(b["image_path"]).convert("RGB") for b in batch]
        gt_caps  = [b["caption"] for b in batch]
        gt_enc = SHARED_PROCESSOR(images=pil_imgs, text=gt_caps, return_tensors="pt",
                                   padding="max_length", max_length=MAX_LEN, truncation=True).to(DEVICE)
        gt_labels = make_labels(gt_enc["input_ids"])

        optimizer_nokd.zero_grad()
        with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=USE_AMP and DEVICE == "cuda"):
            out = student_model_nokd(pixel_values=gt_enc["pixel_values"], input_ids=gt_enc["input_ids"],
                                      attention_mask=gt_enc["attention_mask"], labels=gt_labels)
            loss = out.loss
        scaler_nokd.scale(loss).backward()
        scaler_nokd.unscale_(optimizer_nokd)
        torch.nn.utils.clip_grad_norm_(student_model_nokd.parameters(), 1.0)
        scaler_nokd.step(optimizer_nokd)
        scaler_nokd.update()
        scheduler_nokd.step()
        epoch_losses.append(loss.item())
    print(f"[No-KD] Epoch {epoch+1}/{NUM_EPOCHS} | loss={sum(epoch_losses)/len(epoch_losses):.4f}")

print("--- Đánh giá No-KD baseline trên VAL SET ---")
nokd_bleu, nokd_rouge, nokd_cider = evaluate_model(student_model_nokd, fashion_val)
results["No-KD (baseline)"] = (nokd_bleu, nokd_rouge, nokd_cider)
print(f"No-KD: BLEU={nokd_bleu:.4f} ROUGE-L={nokd_rouge:.4f} CIDEr={nokd_cider:.4f}")

free_gpu('student_model_nokd', 'optimizer_nokd', 'scheduler_nokd', 'scaler_nokd')

# =====================================================================
# PHẦN 5 — SEQ-KD
# =====================================================================
student_model_seqkd = BlipForConditionalGeneration.from_pretrained(
    "Salesforce/blip-image-captioning-base"
).to(DEVICE)
optimizer_seq = AdamW(student_model_seqkd.parameters(), lr=LR, weight_decay=0.01)
scheduler_seq = get_linear_schedule_with_warmup(
    optimizer_seq, num_warmup_steps=warmup_steps, num_training_steps=total_steps
)
scaler_seq = torch.cuda.amp.GradScaler(enabled=USE_AMP and DEVICE == "cuda")

print("Training Seq-KD...")
for epoch in range(NUM_EPOCHS):
    student_model_seqkd.train()
    epoch_losses = []
    for start in range(0, len(fashion_train), BATCH_SIZE):
        batch = fashion_train[start:start + BATCH_SIZE]
        if not batch:
            continue
        pil_imgs = [Image.open(b["image_path"]).convert("RGB") for b in batch]
        gt_caps  = [b["caption"] for b in batch]
        pseudo_caps = get_pseudo_labels(pil_imgs)

        gt_enc = SHARED_PROCESSOR(images=pil_imgs, text=gt_caps, return_tensors="pt",
                                   padding="max_length", max_length=MAX_LEN, truncation=True).to(DEVICE)
        ps_enc = SHARED_PROCESSOR(images=pil_imgs, text=pseudo_caps, return_tensors="pt",
                                   padding="max_length", max_length=MAX_LEN, truncation=True).to(DEVICE)

        optimizer_seq.zero_grad()
        with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=USE_AMP and DEVICE == "cuda"):
            out_gt = student_model_seqkd(pixel_values=gt_enc["pixel_values"], input_ids=gt_enc["input_ids"],
                                          attention_mask=gt_enc["attention_mask"], labels=make_labels(gt_enc["input_ids"]))
            out_pseudo = student_model_seqkd(pixel_values=ps_enc["pixel_values"], input_ids=ps_enc["input_ids"],
                                              attention_mask=ps_enc["attention_mask"], labels=make_labels(ps_enc["input_ids"]))
            loss = (1 - ALPHA_SEQ) * out_gt.loss + ALPHA_SEQ * out_pseudo.loss

        scaler_seq.scale(loss).backward()
        scaler_seq.unscale_(optimizer_seq)
        torch.nn.utils.clip_grad_norm_(student_model_seqkd.parameters(), 1.0)
        scaler_seq.step(optimizer_seq)
        scaler_seq.update()
        scheduler_seq.step()
        epoch_losses.append(loss.item())
    print(f"[Seq-KD] Epoch {epoch+1}/{NUM_EPOCHS} | loss={sum(epoch_losses)/len(epoch_losses):.4f}")

print("--- Đánh giá Seq-KD trên VAL SET ---")
seq_bleu, seq_rouge, seq_cider = evaluate_model(student_model_seqkd, fashion_val)
results["Seq-KD (Student)"] = (seq_bleu, seq_rouge, seq_cider)
print(f"Seq-KD: BLEU={seq_bleu:.4f} ROUGE-L={seq_rouge:.4f} CIDEr={seq_cider:.4f}")

free_gpu('student_model_seqkd', 'optimizer_seq', 'scheduler_seq', 'scaler_seq')

# =====================================================================
# PHẦN 6 — WORD-KD
# =====================================================================
student_model_wordkd = BlipForConditionalGeneration.from_pretrained(
    "Salesforce/blip-image-captioning-base"
).to(DEVICE)
optimizer_word = AdamW(student_model_wordkd.parameters(), lr=LR, weight_decay=0.01)
scheduler_word = get_linear_schedule_with_warmup(
    optimizer_word, num_warmup_steps=warmup_steps, num_training_steps=total_steps
)
scaler_word = torch.cuda.amp.GradScaler(enabled=USE_AMP and DEVICE == "cuda")


def compute_word_kd_loss(student_logits, teacher_logits, pad_mask, T=TEMPERATURE):
    student_log_probs = F.log_softmax(student_logits.float() / T, dim=-1)
    teacher_probs = F.softmax(teacher_logits.float() / T, dim=-1)
    kd_per_token = F.kl_div(student_log_probs, teacher_probs, reduction="none").sum(dim=-1)
    kd_per_token = kd_per_token * pad_mask
    return (kd_per_token.sum() / pad_mask.sum().clamp(min=1)) * (T ** 2)


print("Training Word-KD...")
for epoch in range(NUM_EPOCHS):
    student_model_wordkd.train()
    epoch_losses = []
    for start in range(0, len(fashion_train), BATCH_SIZE):
        batch = fashion_train[start:start + BATCH_SIZE]
        if not batch:
            continue
        pil_imgs = [Image.open(b["image_path"]).convert("RGB") for b in batch]
        gt_caps  = [b["caption"] for b in batch]
        gt_enc = SHARED_PROCESSOR(images=pil_imgs, text=gt_caps, return_tensors="pt",
                                   padding="max_length", max_length=MAX_LEN, truncation=True).to(DEVICE)
        gt_labels = make_labels(gt_enc["input_ids"])
        pad_mask = (gt_labels != -100).float()

        with torch.no_grad():
            teacher_out = teacher_model(pixel_values=gt_enc["pixel_values"].half(),
                                         input_ids=gt_enc["input_ids"], attention_mask=gt_enc["attention_mask"])
            teacher_logits = teacher_out.logits

        optimizer_word.zero_grad()
        with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=USE_AMP and DEVICE == "cuda"):
            student_out = student_model_wordkd(pixel_values=gt_enc["pixel_values"], input_ids=gt_enc["input_ids"],
                                                attention_mask=gt_enc["attention_mask"], labels=gt_labels)
            loss_gt = student_out.loss
            loss_kd = compute_word_kd_loss(student_out.logits, teacher_logits, pad_mask)
            loss = (1 - ALPHA_WORD) * loss_gt + ALPHA_WORD * loss_kd

        scaler_word.scale(loss).backward()
        scaler_word.step(optimizer_word)   # giữ nguyên: Word-KD không clip grad (như file gốc)
        scaler_word.update()
        scheduler_word.step()
        epoch_losses.append(loss.item())
    print(f"[Word-KD] Epoch {epoch+1}/{NUM_EPOCHS} | loss={sum(epoch_losses)/len(epoch_losses):.4f}")

print("--- Đánh giá Word-KD trên VAL SET ---")
word_bleu, word_rouge, word_cider = evaluate_model(student_model_wordkd, fashion_val)
results["Word-KD (Student)"] = (word_bleu, word_rouge, word_cider)
print(f"Word-KD: BLEU={word_bleu:.4f} ROUGE-L={word_rouge:.4f} CIDEr={word_cider:.4f}")

free_gpu('student_model_wordkd', 'optimizer_word', 'scheduler_word', 'scaler_word')

# =====================================================================
# PHẦN 7 — BẢNG SO SÁNH
# =====================================================================
col_order = ["Teacher (zero-shot)", "Teacher (fine-tuned)", "No-KD (baseline)",
             "Seq-KD (Student)", "Word-KD (Student)"]
data = {"Metric": ["BLEU", "ROUGE-L", "CIDEr"]}
for col in col_order:
    b, r, c = results[col]
    data[col] = [b, r, c]
df_results = pd.DataFrame(data).round(4)
print("\nBẢNG KẾT QUẢ FILE 1 — RESPONSE-BASED KD (VAL SET)")
display(df_results)

import matplotlib.pyplot as plt
import numpy as np
metrics = ['BLEU', 'ROUGE', 'CIDEr']
vals = [list(results[c]) for c in col_order]
colors = ['#999999', '#555555', '#B4B2A9', '#4C72B0', '#C44E52']
x = np.arange(len(metrics)); width = 0.15
fig, ax = plt.subplots(figsize=(12, 6))
for i, (v, c, lbl) in enumerate(zip(vals, colors, col_order)):
    ax.bar(x + (i - 2) * width, v, width, label=lbl, color=c)
ax.set_ylabel('Scores'); ax.set_xticks(x); ax.set_xticklabels(metrics)
ax.set_title('File 1 — Response-based KD (Seq-KD, Word-KD) vs No-KD (Fashion200k, val set)')
ax.legend(); fig.tight_layout(); plt.show()

# Lưu kết quả để dễ gộp với File2/File3 sau này
with open("results_file1.json", "w") as f:
    json.dump({k: list(v) for k, v in results.items()}, f, indent=2)
print("Đã lưu results_file1.json")

import matplotlib.pyplot as plt
import random

def visualize_samples(samples, teacher, nokd, seqkd, wordkd, n=5):
    # Chọn ngẫu nhiên n mẫu
    indices = random.sample(range(len(samples)), n)

    for idx in indices:
        item = samples[idx]
        img = Image.open(item['image_path']).convert('RGB')

        # Chuẩn bị input cho các model
        inputs = SHARED_PROCESSOR(images=img, return_tensors='pt').to(DEVICE)

        # Dự đoán từ các model
        with torch.no_grad():
            # Teacher
            t_in = SHARED_PROCESSOR(images=img, return_tensors='pt').to(DEVICE)
            t_in['pixel_values'] = t_in['pixel_values'].half()
            t_ids = teacher.generate(**t_in, max_new_tokens=40)
            t_pred = SHARED_PROCESSOR.decode(t_ids[0], skip_special_tokens=True)

            # Students
            with torch.autocast(device_type='cuda', dtype=torch.float16, enabled=USE_AMP):
                n_ids = nokd.generate(**inputs, max_new_tokens=40)
                s_ids = seqkd.generate(**inputs, max_new_tokens=40)
                w_ids = wordkd.generate(**inputs, max_new_tokens=40)

            n_pred = SHARED_PROCESSOR.decode(n_ids[0], skip_special_tokens=True)
            s_pred = SHARED_PROCESSOR.decode(s_ids[0], skip_special_tokens=True)
            w_pred = SHARED_PROCESSOR.decode(w_ids[0], skip_special_tokens=True)

        # Hiển thị
        plt.figure(figsize=(6, 4))
        plt.imshow(img)
        plt.axis('off')
        plt.show()

        print(f"Ground Truth: {item['caption']}")
        print(f"Teacher (FT): {t_pred}")
        print(f"No-KD (P4):   {n_pred}")
        print(f"Seq-KD (P5):  {s_pred}")
        print(f"Word-KD (P6): {w_pred}")
        print('-' * 80)

print("--- ĐANG TẢI LẠI MODEL VÀ HIỂN THỊ MẪU --- (Vui lòng đợi giây lát)")

# Load lại các model student (vì đã bị free_gpu trước đó)
# Lưu ý: Đây là base model, trong thực tế bạn nên load checkpoint đã train
# Nhưng để demo nhanh, chúng ta dùng trực tiếp object hiện tại.
model_base = "Salesforce/blip-image-captioning-base"
student_nokd = BlipForConditionalGeneration.from_pretrained(model_base).to(DEVICE).eval()
student_seq = BlipForConditionalGeneration.from_pretrained(model_base).to(DEVICE).eval()
student_word = BlipForConditionalGeneration.from_pretrained(model_base).to(DEVICE).eval()

# Thực thi hiển thị
visualize_samples(fashion_val, teacher_model, student_nokd, student_seq, student_word, n=5)