# -*- coding: utf-8 -*-
"""featurekd_fitnets_at_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ravHArfL7-CDrDGgvBGXE_CoQAcuwJND
"""

# -*- coding: utf-8 -*-
"""featurekd_fitnets_at_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k3XZhiMgYnf7sfjNCJlDy0EHyasayIcP
"""

# -*- coding: utf-8 -*-
"""
File2_FeatureKD_FitNets_AT.py

FEATURE-BASED KD: FitNets (pooled feature + Adapter) + Attention Transfer
(spatial attention map, không cần Adapter), so với No-KD baseline.
Teacher: BLIP-large (fine-tune decoder trên Fashion200k trước khi distill).
Student: BLIP-base.

Chạy ĐỘC LẬP trong 1 session Kaggle/Colab riêng — không phụ thuộc File1.
Data (train/val/test) được tải từ 3 file .zip đã chuẩn bị sẵn bởi
prepare_fashion200k_splits.py (sửa 2 URL bên dưới trước khi chạy).
"""

import os
os.environ.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")

!pip install -q pycocoevalcap rouge_score
!pip install -q datasets transformers accelerate Pillow requests nltk evaluate torch torchvision

import gc, json, random, zipfile, urllib.request
import torch
import torch.nn as nn
import torch.nn.functional as F
from PIL import Image
from transformers import (
    BlipProcessor, BlipForConditionalGeneration, get_linear_schedule_with_warmup
)
from torch.optim import AdamW
import evaluate
from pycocoevalcap.cider.cider import Cider
import pandas as pd

RANDOM_SEED = 42
random.seed(RANDOM_SEED)
torch.manual_seed(RANDOM_SEED)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"CUDA available: {torch.cuda.is_available()}")

SHARED_PROCESSOR = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
PAD_ID = SHARED_PROCESSOR.tokenizer.pad_token_id

NUM_EPOCHS   = 10
BATCH_SIZE   = 4
BATCH_SIZE_FEAT = max(1, BATCH_SIZE // 2)
BATCH_SIZE_TEACHER_FT = max(1, BATCH_SIZE // 2)
LR           = 1e-5
MAX_LEN      = 64
WARMUP_RATIO = 0.1
ALPHA_FEAT   = 0.5
ALPHA_AT     = 0.5
TEACHER_FT_EPOCHS = 10
TEACHER_FT_LR = 5e-6
USE_AMP = True

results = {}

def make_labels(input_ids: torch.Tensor) -> torch.Tensor:
    labels = input_ids.clone()
    labels[labels == PAD_ID] = -100
    labels[:, 0] = -100
    return labels

def free_gpu(*names):
    g = globals()
    for name in names:
        if name in g:
            del g[name]
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        torch.cuda.synchronize()
        print(f"   [dọn bộ nhớ] Đang dùng: {torch.cuda.memory_allocated()/1e9:.2f} GB | Đã cấp phát (reserved): {torch.cuda.memory_reserved()/1e9:.2f} GB")

import shutil

# Xóa các file zip lỗi và thư mục giải nén cũ để tải lại sạch sẽ
files_to_remove = ['train.zip', 'val.zip']
dirs_to_remove = ['data_train', 'data_val']

for f in files_to_remove:
    if os.path.exists(f):
        os.remove(f)
        print(f"Đã xóa file lỗi: {f}")

for d in dirs_to_remove:
    if os.path.exists(d):
        shutil.rmtree(d)
        print(f"Đã xóa thư mục cũ: {d}")

print("--- Sẵn sàng để chạy lại ô tải dữ liệu bên trên! ---")

# =====================================================================
# PHẦN 1 — TẢI DATA
# =====================================================================
TRAIN_ZIP_URL = "https://github.com/Q-Anh2610/demo_Lab/raw/main/Tuan_4/dataset/fashion200k_train.zip"
VAL_ZIP_URL   = "https://github.com/Q-Anh2610/demo_Lab/raw/main/Tuan_4/dataset/fashion200k_val.zip"


def load_split_from_zip(zip_path_or_url, split_name):
    target_dir = f"data_{split_name}"
    if zip_path_or_url.startswith("http"):
        local_zip = f"{split_name}.zip"
        if not os.path.exists(local_zip):
            print(f"Đang tải {split_name} từ {zip_path_or_url} ...")
            urllib.request.urlretrieve(zip_path_or_url, local_zip)
    else:
        local_zip = zip_path_or_url

    if not os.path.exists(target_dir):
        with zipfile.ZipFile(local_zip, "r") as zf:
            zf.extractall(target_dir)

    with open(os.path.join(target_dir, "metadata.json"), encoding="utf-8") as f:
        metadata = json.load(f)
    for item in metadata:
        item["image_path"] = os.path.join(target_dir, "images", item["image_file"])
    return metadata


fashion_train = load_split_from_zip(TRAIN_ZIP_URL, "train")
fashion_val   = load_split_from_zip(VAL_ZIP_URL, "val")
print(f"Train: {len(fashion_train)} | Val: {len(fashion_val)}")

steps_per_epoch = max(1, len(fashion_train) // BATCH_SIZE)
total_steps  = steps_per_epoch * NUM_EPOCHS
warmup_steps = int(total_steps * WARMUP_RATIO)

bleu = evaluate.load("bleu")
rouge = evaluate.load("rouge")
cider_scorer = Cider()

def evaluate_model(model, eval_metadata, is_teacher=False, max_samples=None):
    model.eval()
    predictions, references = [], []
    cider_refs, cider_preds = {}, {}
    samples_to_eval = eval_metadata[:max_samples] if max_samples else eval_metadata
    print(f"Đang đánh giá trên {len(samples_to_eval)} mẫu...")

    with torch.no_grad():
        for i, item in enumerate(samples_to_eval):
            img = Image.open(item["image_path"]).convert("RGB")
            inputs = SHARED_PROCESSOR(images=img, return_tensors="pt").to(DEVICE)
            if is_teacher:
                inputs["pixel_values"] = inputs["pixel_values"].half()
                generated_ids = model.generate(**inputs, max_new_tokens=40)
            else:
                with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=USE_AMP and DEVICE == "cuda"):
                    generated_ids = model.generate(**inputs, max_new_tokens=40)
            pred = SHARED_PROCESSOR.decode(generated_ids[0], skip_special_tokens=True)
            predictions.append(pred)
            references.append([item["caption"]])
            cider_preds[i] = [pred]
            cider_refs[i] = [item["caption"]]

    bleu_score  = bleu.compute(predictions=predictions, references=references)["bleu"]
    rouge_score = rouge.compute(predictions=predictions, references=references)["rougeL"]
    (cider_score, _) = cider_scorer.compute_score(cider_refs, cider_preds)
    return bleu_score, rouge_score, cider_score

def visualize_samples(samples, teacher, nokd, fitnets, at, n=5):
    # Chọn ngẫu nhiên n mẫu
    indices = random.sample(range(len(samples)), n)

    for idx in indices:
        item = samples[idx]
        img = Image.open(item['image_path']).convert('RGB')

        # Chuẩn bị input cho các model
        inputs = SHARED_PROCESSOR(images=img, return_tensors='pt').to(DEVICE)

        # Dự đoán từ các model
        with torch.no_grad():
            # Teacher
            t_in = SHARED_PROCESSOR(images=img, return_tensors='pt').to(DEVICE)
            t_in['pixel_values'] = t_in['pixel_values'].half()
            t_ids = teacher.generate(**t_in, max_new_tokens=40)
            t_pred = SHARED_PROCESSOR.decode(t_ids[0], skip_special_tokens=True)

            # Students
            with torch.autocast(device_type='cuda', dtype=torch.float16, enabled=USE_AMP):
                n_ids = nokd.generate(**inputs, max_new_tokens=40)
                f_ids = fitnets.generate(**inputs, max_new_tokens=40)
                a_ids = at.generate(**inputs, max_new_tokens=40)

            n_pred = SHARED_PROCESSOR.decode(n_ids[0], skip_special_tokens=True)
            f_pred = SHARED_PROCESSOR.decode(f_ids[0], skip_special_tokens=True)
            a_pred = SHARED_PROCESSOR.decode(a_ids[0], skip_special_tokens=True)

        # Hiển thị
        plt.figure(figsize=(6, 4))
        plt.imshow(img)
        plt.axis('off')
        plt.show()

        print(f"Ground Truth:       {item['caption']}")
        print(f"Teacher (FT):       {t_pred}")
        print(f"No-KD (baseline):   {n_pred}")
        print(f"FitNets:            {f_pred}")
        print(f"Attention Transfer: {a_pred}")
        print('-' * 80)

teacher_model = BlipForConditionalGeneration.from_pretrained(
    "Salesforce/blip-image-captioning-large", torch_dtype=torch.float16
).to(DEVICE).eval()
for p in teacher_model.parameters():
    p.requires_grad = False

print("--- Đánh giá Teacher (zero-shot) trên VAL SET ---")
teach_zs_bleu, teach_zs_rouge, teach_zs_cider = evaluate_model(teacher_model, fashion_val, is_teacher=True)
results["Teacher (zero-shot)"] = (teach_zs_bleu, teach_zs_rouge, teach_zs_cider)

for p in teacher_model.parameters():
    p.requires_grad = True
for p in teacher_model.vision_model.parameters():
    p.requires_grad = False
trainable_teacher_params = [p for p in teacher_model.parameters() if p.requires_grad]

for name, module in teacher_model.named_children():
    if name != "vision_model": module.float()

try:
    teacher_model.gradient_checkpointing_enable()
except Exception:
    pass

optimizer_teacher = AdamW(trainable_teacher_params, lr=TEACHER_FT_LR, weight_decay=0.01)
t_steps = max(1, len(fashion_train) // BATCH_SIZE_TEACHER_FT) * TEACHER_FT_EPOCHS
scheduler_teacher = get_linear_schedule_with_warmup(optimizer_teacher, num_warmup_steps=int(t_steps * WARMUP_RATIO), num_training_steps=t_steps)
scaler_teacher = torch.amp.GradScaler('cuda', enabled=USE_AMP and DEVICE == "cuda")

print(f"Fine-tune Teacher: {TEACHER_FT_EPOCHS} epochs | batch_size={BATCH_SIZE_TEACHER_FT}")
best_val_loss_teacher = float('inf')
best_teacher_path = "best_teacher.pth"

for epoch in range(TEACHER_FT_EPOCHS):
    teacher_model.train()
    epoch_losses = []
    for start in range(0, len(fashion_train), BATCH_SIZE_TEACHER_FT):
        batch = fashion_train[start:start + BATCH_SIZE_TEACHER_FT]
        if not batch: continue
        pil_imgs = [Image.open(b["image_path"]).convert("RGB") for b in batch]
        gt_caps  = [b["caption"] for b in batch]
        gt_enc = SHARED_PROCESSOR(images=pil_imgs, text=gt_caps, return_tensors="pt", padding="max_length", max_length=MAX_LEN, truncation=True).to(DEVICE)
        gt_labels = make_labels(gt_enc["input_ids"])

        optimizer_teacher.zero_grad()
        with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=USE_AMP and DEVICE == "cuda"):
            out = teacher_model(pixel_values=gt_enc["pixel_values"], input_ids=gt_enc["input_ids"], attention_mask=gt_enc["attention_mask"], labels=gt_labels)
            loss = out.loss
        scaler_teacher.scale(loss).backward()
        scaler_teacher.unscale_(optimizer_teacher)
        torch.nn.utils.clip_grad_norm_(trainable_teacher_params, 1.0)
        scaler_teacher.step(optimizer_teacher)
        scaler_teacher.update()
        scheduler_teacher.step()
        epoch_losses.append(loss.item())

    teacher_model.eval()
    val_losses = []
    with torch.no_grad():
        for s_val in range(0, len(fashion_val), BATCH_SIZE_TEACHER_FT):
            b_val = fashion_val[s_val:s_val + BATCH_SIZE_TEACHER_FT]
            if not b_val: continue
            p_imgs = [Image.open(b["image_path"]).convert("RGB") for b in b_val]
            g_caps = [b["caption"] for b in b_val]
            g_enc = SHARED_PROCESSOR(images=p_imgs, text=g_caps, return_tensors="pt", padding="max_length", max_length=MAX_LEN, truncation=True).to(DEVICE)
            g_labels = make_labels(g_enc["input_ids"])
            with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=USE_AMP and DEVICE == "cuda"):
                o_val = teacher_model(**g_enc, labels=g_labels)
            val_losses.append(o_val.loss.item())
    v_loss = sum(val_losses)/len(val_losses)
    print(f"[Teacher FT] Epoch {epoch+1}/{TEACHER_FT_EPOCHS} | loss={sum(epoch_losses)/len(epoch_losses):.4f} | val_loss={v_loss:.4f}")

    if v_loss < best_val_loss_teacher:
        best_val_loss_teacher = v_loss
        torch.save(teacher_model.state_dict(), best_teacher_path)
        print("   --> Lưu checkpoint Teacher tốt nhất")

try: teacher_model.gradient_checkpointing_disable()
except Exception: pass

teacher_model.load_state_dict(torch.load(best_teacher_path))
teacher_model = teacher_model.half().eval()
for p in teacher_model.parameters(): p.requires_grad = False
free_gpu('optimizer_teacher', 'scheduler_teacher', 'scaler_teacher')

print("--- Đánh giá Teacher (fine-tuned) trên VAL SET ---")
teach_ft_bleu, teach_ft_rouge, teach_ft_cider = evaluate_model(teacher_model, fashion_val, is_teacher=True)
results["Teacher (fine-tuned)"] = (teach_ft_bleu, teach_ft_rouge, teach_ft_cider)

student_model_nokd = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base").to(DEVICE)
optimizer_nokd = AdamW(student_model_nokd.parameters(), lr=LR, weight_decay=0.01)
scheduler_nokd = get_linear_schedule_with_warmup(optimizer_nokd, num_warmup_steps=warmup_steps, num_training_steps=total_steps)
scaler_nokd = torch.amp.GradScaler('cuda', enabled=USE_AMP and DEVICE == "cuda")

print("Training No-KD baseline...")
best_val_loss_nokd = float('inf'); best_nokd_path = "best_student_nokd.pth"

for epoch in range(NUM_EPOCHS):
    student_model_nokd.train(); epoch_losses = []
    for start in range(0, len(fashion_train), BATCH_SIZE):
        batch = fashion_train[start:start + BATCH_SIZE]
        if not batch: continue
        pil_imgs = [Image.open(b["image_path"]).convert("RGB") for b in batch]
        gt_caps  = [b["caption"] for b in batch]
        gt_enc = SHARED_PROCESSOR(images=pil_imgs, text=gt_caps, return_tensors="pt", padding="max_length", max_length=MAX_LEN, truncation=True).to(DEVICE)
        gt_labels = make_labels(gt_enc["input_ids"])

        optimizer_nokd.zero_grad()
        with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=USE_AMP and DEVICE == "cuda"):
            out = student_model_nokd(**gt_enc, labels=gt_labels)
            loss = out.loss
        scaler_nokd.scale(loss).backward()
        scaler_nokd.unscale_(optimizer_nokd)
        torch.nn.utils.clip_grad_norm_(student_model_nokd.parameters(), 1.0)
        scaler_nokd.step(optimizer_nokd); scaler_nokd.update(); scheduler_nokd.step()
        epoch_losses.append(loss.item())

    student_model_nokd.eval(); val_losses = []
    with torch.no_grad():
        for s_v in range(0, len(fashion_val), BATCH_SIZE):
            b_v = fashion_val[s_v:s_v + BATCH_SIZE]
            if not b_v: continue
            p_i = [Image.open(b["image_path"]).convert("RGB") for b in b_v]
            g_c = [b["caption"] for b in b_v]
            g_e = SHARED_PROCESSOR(images=p_i, text=g_c, return_tensors="pt", padding="max_length", max_length=MAX_LEN, truncation=True).to(DEVICE)
            with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=USE_AMP and DEVICE == "cuda"):
                o_v = student_model_nokd(**g_e, labels=make_labels(g_e["input_ids"]))
            val_losses.append(o_v.loss.item())
    v_loss = sum(val_losses)/len(val_losses)
    print(f"[No-KD] Epoch {epoch+1}/{NUM_EPOCHS} | loss={sum(epoch_losses)/len(epoch_losses):.4f} | val_loss={v_loss:.4f}")
    if v_loss < best_val_loss_nokd:
        best_val_loss_nokd = v_loss; torch.save(student_model_nokd.state_dict(), best_nokd_path)
        print("   --> Lưu checkpoint No-KD tốt nhất")

student_model_nokd.load_state_dict(torch.load(best_nokd_path))
print("--- Đánh giá No-KD baseline trên VAL SET ---")
nokd_bleu, nokd_rouge, nokd_cider = evaluate_model(student_model_nokd, fashion_val)
results["No-KD (baseline)"] = (nokd_bleu, nokd_rouge, nokd_cider)
free_gpu('student_model_nokd', 'optimizer_nokd', 'scheduler_nokd', 'scaler_nokd')

def get_pooled_image_feature(model, pixel_values):
    vision_out = model.vision_model(pixel_values=pixel_values)
    return vision_out.pooler_output

student_model_fitnets = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base").to(DEVICE)
t_h = teacher_model.vision_model.config.hidden_size
s_h = student_model_fitnets.vision_model.config.hidden_size
adapter_fitnets = nn.Linear(s_h, t_h).to(DEVICE)

optimizer_fitnets = AdamW(list(student_model_fitnets.parameters()) + list(adapter_fitnets.parameters()), lr=LR, weight_decay=0.01)
feat_steps = max(1, len(fashion_train) // BATCH_SIZE_FEAT) * NUM_EPOCHS
scheduler_fitnets = get_linear_schedule_with_warmup(optimizer_fitnets, num_warmup_steps=int(feat_steps * WARMUP_RATIO), num_training_steps=feat_steps)
scaler_fitnets = torch.amp.GradScaler('cuda', enabled=USE_AMP and DEVICE == "cuda")

print(f"Training FitNets (batch_size={BATCH_SIZE_FEAT})...")
best_val_loss_fitnets = float('inf'); best_fitnets_path = "best_student_fitnets.pth"

def validate_fitnets():
    student_model_fitnets.eval(); adapter_fitnets.eval()
    val_losses = []
    with torch.no_grad():
        for s_v in range(0, len(fashion_val), BATCH_SIZE_FEAT):
            b_v = fashion_val[s_v:s_v + BATCH_SIZE_FEAT]
            if not b_v: continue
            p_i = [Image.open(b["image_path"]).convert("RGB") for b in b_v]
            g_c = [b["caption"] for b in b_v]
            g_e = SHARED_PROCESSOR(images=p_i, text=g_c, return_tensors="pt", padding="max_length", max_length=MAX_LEN, truncation=True).to(DEVICE)
            t_f = get_pooled_image_feature(teacher_model, g_e["pixel_values"].half()).float()
            with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=USE_AMP and DEVICE == "cuda"):
                s_f = get_pooled_image_feature(student_model_fitnets, g_e["pixel_values"])
                a_f = adapter_fitnets(s_f)
                l_f = F.mse_loss(a_f.float(), t_f)
                o_g = student_model_fitnets(**g_e, labels=make_labels(g_e["input_ids"]))
                l_v = (1 - ALPHA_FEAT) * o_g.loss + ALPHA_FEAT * l_f
            val_losses.append(l_v.item())
    student_model_fitnets.train(); adapter_fitnets.train()
    return sum(val_losses) / len(val_losses)

# QUAN TRỌNG: BATCH_SIZE_FEAT = BATCH_SIZE // 2 -> mỗi epoch FitNets có GẤP ĐÔI số
# step update so với No-KD/Seq-KD/Word-KD (cùng NUM_EPOCHS nhưng batch nhỏ hơn).
# Nếu vẫn validate 1 lần/epoch như cũ, FitNets dễ "vượt qua" điểm val_loss tối ưu
# NGAY TRONG một epoch trước khi kịp lưu checkpoint -> checkpoint chọn ra không còn
# là tốt nhất thật sự. Do đó validate theo SỐ STEP (không theo epoch), cùng độ phân
# giải với BATCH_SIZE đầy đủ, để công bằng khi so sánh giữa các phương pháp.
check_every_fitnets = max(1, len(fashion_train) // BATCH_SIZE)
global_step_fitnets = 0

for epoch in range(NUM_EPOCHS):
    student_model_fitnets.train(); adapter_fitnets.train(); epoch_losses = []
    for start in range(0, len(fashion_train), BATCH_SIZE_FEAT):
        batch = fashion_train[start:start + BATCH_SIZE_FEAT]
        if not batch: continue
        pil_imgs = [Image.open(b["image_path"]).convert("RGB") for b in batch]
        gt_caps  = [b["caption"] for b in batch]
        gt_enc = SHARED_PROCESSOR(images=pil_imgs, text=gt_caps, return_tensors="pt", padding="max_length", max_length=MAX_LEN, truncation=True).to(DEVICE)
        gt_labels = make_labels(gt_enc["input_ids"])
        with torch.no_grad(): teacher_feat = get_pooled_image_feature(teacher_model, gt_enc["pixel_values"].half()).float()

        optimizer_fitnets.zero_grad()
        with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=USE_AMP and DEVICE == "cuda"):
            student_feat = get_pooled_image_feature(student_model_fitnets, gt_enc["pixel_values"])
            adapted_feat = adapter_fitnets(student_feat)
            loss_f = F.mse_loss(adapted_feat.float(), teacher_feat)
            out_gt = student_model_fitnets(**gt_enc, labels=gt_labels)
            loss = (1 - ALPHA_FEAT) * out_gt.loss + ALPHA_FEAT * loss_f
        scaler_fitnets.scale(loss).backward(); scaler_fitnets.unscale_(optimizer_fitnets)
        torch.nn.utils.clip_grad_norm_(list(student_model_fitnets.parameters()) + list(adapter_fitnets.parameters()), 1.0)
        scaler_fitnets.step(optimizer_fitnets); scaler_fitnets.update(); scheduler_fitnets.step()
        epoch_losses.append(loss.item())
        global_step_fitnets += 1

        if global_step_fitnets % check_every_fitnets == 0:
            v_loss = validate_fitnets()
            print(f"   [FitNets] step {global_step_fitnets} (epoch {epoch+1}) | val={v_loss:.4f}")
            if v_loss < best_val_loss_fitnets:
                best_val_loss_fitnets = v_loss
                torch.save(student_model_fitnets.state_dict(), best_fitnets_path)
                print("      --> Lưu checkpoint FitNets tốt nhất")

    print(f"[FitNets] Epoch {epoch+1}/{NUM_EPOCHS} | loss={sum(epoch_losses)/len(epoch_losses):.4f}")

# Validate lần cuối (phòng trường hợp số step cuối cùng không rơi đúng mốc check_every)
v_loss = validate_fitnets()
if v_loss < best_val_loss_fitnets:
    best_val_loss_fitnets = v_loss
    torch.save(student_model_fitnets.state_dict(), best_fitnets_path)
    print("   --> Lưu checkpoint FitNets tốt nhất (cuối cùng)")

student_model_fitnets.load_state_dict(torch.load(best_fitnets_path))
print("--- Đánh giá FitNets trên VAL SET ---")
fit_b, fit_r, fit_c = evaluate_model(student_model_fitnets, fashion_val)
results["FitNets (Student)"] = (fit_b, fit_r, fit_c)
free_gpu('student_model_fitnets', 'adapter_fitnets', 'optimizer_fitnets', 'scheduler_fitnets', 'scaler_fitnets')

def get_attention_map(hidden_states, eps=1e-6):
    att = hidden_states.pow(2).sum(dim=-1)
    return F.normalize(att, p=2, dim=1, eps=eps)

def get_last_hidden_states(model, pixel_values):
    vision_out = model.vision_model(pixel_values=pixel_values, output_hidden_states=True)
    return vision_out.hidden_states[-1]

student_model_at = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base").to(DEVICE)
optimizer_at = AdamW(student_model_at.parameters(), lr=LR, weight_decay=0.01)
scheduler_at = get_linear_schedule_with_warmup(optimizer_at, num_warmup_steps=int(feat_steps * WARMUP_RATIO), num_training_steps=feat_steps)
scaler_at = torch.amp.GradScaler('cuda', enabled=USE_AMP and DEVICE == "cuda")

print(f"Training Attention Transfer (batch_size={BATCH_SIZE_FEAT})...")
best_val_loss_at = float('inf'); best_at_path = "best_student_at.pth"

def validate_at():
    student_model_at.eval()
    val_losses = []
    with torch.no_grad():
        for s_v in range(0, len(fashion_val), BATCH_SIZE_FEAT):
            b_v = fashion_val[s_v:s_v + BATCH_SIZE_FEAT]
            if not b_v: continue
            p_i = [Image.open(b["image_path"]).convert("RGB") for b in b_v]
            g_e = SHARED_PROCESSOR(images=p_i, text=[b["caption"] for b in b_v], return_tensors="pt", padding="max_length", max_length=MAX_LEN, truncation=True).to(DEVICE)
            t_a = get_attention_map(get_last_hidden_states(teacher_model, g_e["pixel_values"].half()).float())
            with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=USE_AMP and DEVICE == "cuda"):
                s_a = get_attention_map(get_last_hidden_states(student_model_at, g_e["pixel_values"]).float())
                l_a_v = F.mse_loss(s_a, t_a)
                o_v = student_model_at(**g_e, labels=make_labels(g_e["input_ids"]))
                l_v = (1 - ALPHA_AT) * o_v.loss + ALPHA_AT * l_a_v
            val_losses.append(l_v.item())
    student_model_at.train()
    return sum(val_losses) / len(val_losses)

# Cùng lý do như FitNets: BATCH_SIZE_FEAT nhỏ hơn -> gấp đôi số step/epoch so với
# No-KD/Seq-KD/Word-KD -> validate theo SỐ STEP để cùng độ phân giải giám sát.
check_every_at = max(1, len(fashion_train) // BATCH_SIZE)
global_step_at = 0

for epoch in range(NUM_EPOCHS):
    student_model_at.train(); epoch_losses = []
    for start in range(0, len(fashion_train), BATCH_SIZE_FEAT):
        batch = fashion_train[start:start + BATCH_SIZE_FEAT]
        if not batch: continue
        pil_imgs = [Image.open(b["image_path"]).convert("RGB") for b in batch]
        gt_caps  = [b["caption"] for b in batch]
        gt_enc = SHARED_PROCESSOR(images=pil_imgs, text=gt_caps, return_tensors="pt", padding="max_length", max_length=MAX_LEN, truncation=True).to(DEVICE)
        with torch.no_grad(): t_att = get_attention_map(get_last_hidden_states(teacher_model, gt_enc["pixel_values"].half()).float())

        optimizer_at.zero_grad()
        with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=USE_AMP and DEVICE == "cuda"):
            s_h = get_last_hidden_states(student_model_at, gt_enc["pixel_values"])
            s_att = get_attention_map(s_h.float())
            l_at = F.mse_loss(s_att, t_att)
            out = student_model_at(**gt_enc, labels=make_labels(gt_enc["input_ids"]))
            loss = (1 - ALPHA_AT) * out.loss + ALPHA_AT * l_at
        scaler_at.scale(loss).backward(); scaler_at.unscale_(optimizer_at)
        torch.nn.utils.clip_grad_norm_(student_model_at.parameters(), 1.0)
        scaler_at.step(optimizer_at); scaler_at.update(); scheduler_at.step()
        epoch_losses.append(loss.item())
        global_step_at += 1

        if global_step_at % check_every_at == 0:
            v_l = validate_at()
            print(f"   [AT] step {global_step_at} (epoch {epoch+1}) | val={v_l:.4f}")
            if v_l < best_val_loss_at:
                best_val_loss_at = v_l
                torch.save(student_model_at.state_dict(), best_at_path)
                print("      --> Lưu checkpoint AT tốt nhất")

    print(f"[AT] Epoch {epoch+1}/{NUM_EPOCHS} | loss={sum(epoch_losses)/len(epoch_losses):.4f}")

# Validate lần cuối (phòng trường hợp số step cuối cùng không rơi đúng mốc check_every)
v_l = validate_at()
if v_l < best_val_loss_at:
    best_val_loss_at = v_l
    torch.save(student_model_at.state_dict(), best_at_path)
    print("   --> Lưu checkpoint AT tốt nhất (cuối cùng)")

student_model_at.load_state_dict(torch.load(best_at_path))
print("--- Đánh giá AT trên VAL SET ---")
at_b, at_r, at_c = evaluate_model(student_model_at, fashion_val)
results["Attention Transfer (Student)"] = (at_b, at_r, at_c)
free_gpu('student_model_at', 'optimizer_at', 'scheduler_at', 'scaler_at')

# =====================================================================
# PHẦN 7 — BẢNG SO SÁNH
# =====================================================================
col_order = ["Teacher (zero-shot)", "Teacher (fine-tuned)", "No-KD (baseline)",
             "FitNets (Student)", "Attention Transfer (Student)"]
data = {"Metric": ["BLEU", "ROUGE-L", "CIDEr"]}
for col in col_order:
    b, r, c = results[col]
    data[col] = [b, r, c]
df_results = pd.DataFrame(data).round(4)
print("\nBẢNG KẾT QUẢ FILE 2 — FEATURE-BASED KD (VAL SET)")
display(df_results)

import matplotlib.pyplot as plt
import numpy as np
metrics = ['BLEU', 'ROUGE', 'CIDEr']
vals = [list(results[c]) for c in col_order]
colors = ['#999999', '#555555', '#B4B2A9', '#55A868', '#8172B2']
x = np.arange(len(metrics)); width = 0.15
fig, ax = plt.subplots(figsize=(12, 6))
for i, (v, c, lbl) in enumerate(zip(vals, colors, col_order)):
    ax.bar(x + (i - 2) * width, v, width, label=lbl, color=c)
ax.set_ylabel('Scores'); ax.set_xticks(x); ax.set_xticklabels(metrics)
ax.set_title('File 2 — Feature-based KD (FitNets, Attention Transfer) vs No-KD (Fashion200k, val set)')
ax.legend(); fig.tight_layout(); plt.show()

with open("results_file2.json", "w") as f:
    json.dump({k: list(v) for k, v in results.items()}, f, indent=2)
print("Đã lưu results_file2.json")

import matplotlib.pyplot as plt
import random

def visualize_samples(samples, teacher, nokd, fitnets, at, n=5):
    # Chọn ngẫu nhiên n mẫu
    indices = random.sample(range(len(samples)), n)

    for idx in indices:
        item = samples[idx]
        img = Image.open(item['image_path']).convert('RGB')

        # Chuẩn bị input cho các model
        inputs = SHARED_PROCESSOR(images=img, return_tensors='pt').to(DEVICE)

        # Dự đoán từ các model
        with torch.no_grad():
            # Teacher
            t_in = SHARED_PROCESSOR(images=img, return_tensors='pt').to(DEVICE)
            t_in['pixel_values'] = t_in['pixel_values'].half()
            t_ids = teacher.generate(**t_in, max_new_tokens=40)
            t_pred = SHARED_PROCESSOR.decode(t_ids[0], skip_special_tokens=True)

            # Students
            with torch.autocast(device_type='cuda', dtype=torch.float16, enabled=USE_AMP):
                n_ids = nokd.generate(**inputs, max_new_tokens=40)
                f_ids = fitnets.generate(**inputs, max_new_tokens=40)
                a_ids = at.generate(**inputs, max_new_tokens=40)

            n_pred = SHARED_PROCESSOR.decode(n_ids[0], skip_special_tokens=True)
            f_pred = SHARED_PROCESSOR.decode(f_ids[0], skip_special_tokens=True)
            a_pred = SHARED_PROCESSOR.decode(a_ids[0], skip_special_tokens=True)

        # Hiển thị
        plt.figure(figsize=(6, 4))
        plt.imshow(img)
        plt.axis('off')
        plt.show()

        print(f"Ground Truth: {item['caption']}")
        print(f"Teacher (FT):        {t_pred}")
        print(f"No-KD (baseline):    {n_pred}")
        print(f"FitNets (Student):   {f_pred}")
        print(f"Attn Transfer (Std): {a_pred}")
        print('-' * 80)

print("--- ĐANG TẢI LẠI MODEL TỪ CHECKPOINT TỐT NHẤT VÀ HIỂN THỊ MẪU --- (Vui lòng đợi giây lát)")

# v2: Load lại các model student TỪ CHECKPOINT TỐT NHẤT đã lưu trong lúc train
# (khác bản gốc: bản gốc load base weights ngẫu nhiên, không phản ánh đúng
# model đã train xong).
model_base = "Salesforce/blip-image-captioning-base"

student_nokd = BlipForConditionalGeneration.from_pretrained(model_base).to(DEVICE)
student_nokd.load_state_dict(torch.load(best_nokd_path))
student_nokd = student_nokd.eval()

student_fitnets = BlipForConditionalGeneration.from_pretrained(model_base).to(DEVICE)
student_fitnets.load_state_dict(torch.load(best_fitnets_path))
student_fitnets = student_fitnets.eval()

student_at = BlipForConditionalGeneration.from_pretrained(model_base).to(DEVICE)
student_at.load_state_dict(torch.load(best_at_path))
student_at = student_at.eval()

# Thực thi hiển thị
visualize_samples(fashion_val, teacher_model, student_nokd, student_fitnets, student_at, n=5)