# -*- coding: utf-8 -*-
"""featurekd_fitnets_at.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16ytXQAYL-P_2dejlOJwaAlD78dnUMgMT
"""

# -*- coding: utf-8 -*-
"""
File2_FeatureKD_FitNets_AT.py

FEATURE-BASED KD: FitNets (pooled feature + Adapter) + Attention Transfer
(spatial attention map, không cần Adapter), so với No-KD baseline.
Teacher: BLIP-large (fine-tune decoder trên Fashion200k trước khi distill).
Student: BLIP-base.

Chạy ĐỘC LẬP trong 1 session Kaggle/Colab riêng — không phụ thuộc File1.
Data (train/val/test) được tải từ 3 file .zip đã chuẩn bị sẵn bởi
prepare_fashion200k_splits.py (sửa 2 URL bên dưới trước khi chạy).
"""

# =====================================================================
# PHẦN 0 — CÀI ĐẶT & IMPORT
# =====================================================================
import os
os.environ.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")

!pip install -q pycocoevalcap rouge_score
!pip install -q datasets transformers accelerate Pillow requests nltk evaluate torch torchvision

import gc, json, random, zipfile, urllib.request
import torch
import torch.nn as nn
import torch.nn.functional as F
from PIL import Image
from transformers import (
    BlipProcessor, BlipForConditionalGeneration, get_linear_schedule_with_warmup
)
from torch.optim import AdamW
import evaluate
from pycocoevalcap.cider.cider import Cider
import pandas as pd

RANDOM_SEED = 42
random.seed(RANDOM_SEED)
torch.manual_seed(RANDOM_SEED)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"CUDA available: {torch.cuda.is_available()}")

SHARED_PROCESSOR = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
PAD_ID = SHARED_PROCESSOR.tokenizer.pad_token_id

NUM_EPOCHS   = 10
BATCH_SIZE   = 4
BATCH_SIZE_FEAT = max(1, BATCH_SIZE // 2)  # feature-based nặng hơn (2 forward vision/step) -> batch nhỏ hơn
BATCH_SIZE_TEACHER_FT = max(1, BATCH_SIZE // 2)
LR           = 1e-5
MAX_LEN      = 64
WARMUP_RATIO = 0.1
ALPHA_FEAT   = 0.5   # trọng số FitNets
ALPHA_AT     = 0.5   # trọng số Attention Transfer
TEACHER_FT_EPOCHS = 5
TEACHER_FT_LR = 5e-6
USE_AMP = True

results = {}


def make_labels(input_ids: torch.Tensor) -> torch.Tensor:
    labels = input_ids.clone()
    labels[labels == PAD_ID] = -100
    labels[:, 0] = -100
    return labels


def free_gpu(*names):
    """Xóa biến TOÀN CỤC theo TÊN (chuỗi) rồi dọn rác + cache CUDA.
    Phải truyền tên dạng chuỗi (vd free_gpu('model_x', 'optimizer_x')), KHÔNG
    truyền thẳng object — truyền object chỉ xóa được tham chiếu cục bộ bên
    trong hàm, biến toàn cục ngoài vẫn giữ nguyên -> không giải phóng được
    bộ nhớ GPU thật sự."""
    g = globals()
    for name in names:
        if name in g:
            del g[name]
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        torch.cuda.synchronize()
        print(f"   [dọn bộ nhớ] Đang dùng: {torch.cuda.memory_allocated()/1e9:.2f} GB "
              f"| Đã cấp phát (reserved): {torch.cuda.memory_reserved()/1e9:.2f} GB")

import shutil

# Xóa các file zip lỗi và thư mục giải nén cũ để tải lại sạch sẽ
files_to_remove = ['train.zip', 'val.zip']
dirs_to_remove = ['data_train', 'data_val']

for f in files_to_remove:
    if os.path.exists(f):
        os.remove(f)
        print(f"Đã xóa file lỗi: {f}")

for d in dirs_to_remove:
    if os.path.exists(d):
        shutil.rmtree(d)
        print(f"Đã xóa thư mục cũ: {d}")

print("--- Sẵn sàng để chạy lại ô tải dữ liệu bên trên! ---")

# =====================================================================
# PHẦN 1 — TẢI DATA
# =====================================================================
TRAIN_ZIP_URL = "https://github.com/Q-Anh2610/demo_Lab/raw/main/Tuan_4/dataset/fashion200k_train.zip"
VAL_ZIP_URL   = "https://github.com/Q-Anh2610/demo_Lab/raw/main/Tuan_4/dataset/fashion200k_val.zip"


def load_split_from_zip(zip_path_or_url, split_name):
    target_dir = f"data_{split_name}"
    if zip_path_or_url.startswith("http"):
        local_zip = f"{split_name}.zip"
        if not os.path.exists(local_zip):
            print(f"Đang tải {split_name} từ {zip_path_or_url} ...")
            urllib.request.urlretrieve(zip_path_or_url, local_zip)
    else:
        local_zip = zip_path_or_url

    if not os.path.exists(target_dir):
        with zipfile.ZipFile(local_zip, "r") as zf:
            zf.extractall(target_dir)

    with open(os.path.join(target_dir, "metadata.json"), encoding="utf-8") as f:
        metadata = json.load(f)
    for item in metadata:
        item["image_path"] = os.path.join(target_dir, "images", item["image_file"])
    return metadata


fashion_train = load_split_from_zip(TRAIN_ZIP_URL, "train")
fashion_val   = load_split_from_zip(VAL_ZIP_URL, "val")
print(f"Train: {len(fashion_train)} | Val: {len(fashion_val)}")

steps_per_epoch = max(1, len(fashion_train) // BATCH_SIZE)
total_steps  = steps_per_epoch * NUM_EPOCHS
warmup_steps = int(total_steps * WARMUP_RATIO)

# =====================================================================
# PHẦN 2 — HÀM ĐÁNH GIÁ
# =====================================================================
bleu = evaluate.load("bleu")
rouge = evaluate.load("rouge")
cider_scorer = Cider()


def evaluate_model(model, eval_metadata, is_teacher=False, max_samples=None):
    model.eval()
    predictions, references = [], []
    cider_refs, cider_preds = {}, {}
    samples_to_eval = eval_metadata[:max_samples] if max_samples else eval_metadata
    print(f"Đang đánh giá trên {len(samples_to_eval)} mẫu...")

    with torch.no_grad():
        for i, item in enumerate(samples_to_eval):
            img = Image.open(item["image_path"]).convert("RGB")
            inputs = SHARED_PROCESSOR(images=img, return_tensors="pt").to(DEVICE)
            if is_teacher:
                inputs["pixel_values"] = inputs["pixel_values"].half()
                generated_ids = model.generate(**inputs, max_new_tokens=40)
            else:
                with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=USE_AMP and DEVICE == "cuda"):
                    generated_ids = model.generate(**inputs, max_new_tokens=40)
            pred = SHARED_PROCESSOR.decode(generated_ids[0], skip_special_tokens=True)
            predictions.append(pred)
            references.append([item["caption"]])
            cider_preds[i] = [pred]
            cider_refs[i] = [item["caption"]]

    bleu_score  = bleu.compute(predictions=predictions, references=references)["bleu"]
    rouge_score = rouge.compute(predictions=predictions, references=references)["rougeL"]
    (cider_score, _) = cider_scorer.compute_score(cider_refs, cider_preds)
    return bleu_score, rouge_score, cider_score

# =====================================================================
# PHẦN 3 — TEACHER (BLIP-large): zero-shot -> fine-tune decoder -> đóng băng
# =====================================================================
teacher_model = BlipForConditionalGeneration.from_pretrained(
    "Salesforce/blip-image-captioning-large", torch_dtype=torch.float16
).to(DEVICE).eval()
for p in teacher_model.parameters():
    p.requires_grad = False

print("--- Đánh giá Teacher (zero-shot) trên VAL SET ---")
teach_zs_bleu, teach_zs_rouge, teach_zs_cider = evaluate_model(teacher_model, fashion_val, is_teacher=True)
results["Teacher (zero-shot)"] = (teach_zs_bleu, teach_zs_rouge, teach_zs_cider)
print(f"Teacher (zero-shot): BLEU={teach_zs_bleu:.4f} ROUGE-L={teach_zs_rouge:.4f} CIDEr={teach_zs_cider:.4f}")

for p in teacher_model.parameters():
    p.requires_grad = True
for p in teacher_model.vision_model.parameters():
    p.requires_grad = False
trainable_teacher_params = [p for p in teacher_model.parameters() if p.requires_grad]
print(f"Số tham số Teacher sẽ fine-tune: {sum(p.numel() for p in trainable_teacher_params)/1e6:.1f}M")

for name, module in teacher_model.named_children():
    if name != "vision_model":
        module.float()

try:
    teacher_model.gradient_checkpointing_enable()
except Exception as e:
    print(f"Không bật được gradient checkpointing: {e}")

optimizer_teacher = AdamW(trainable_teacher_params, lr=TEACHER_FT_LR, weight_decay=0.01)
t_steps = max(1, len(fashion_train) // BATCH_SIZE_TEACHER_FT) * TEACHER_FT_EPOCHS
scheduler_teacher = get_linear_schedule_with_warmup(
    optimizer_teacher, num_warmup_steps=int(t_steps * WARMUP_RATIO), num_training_steps=t_steps
)
scaler_teacher = torch.cuda.amp.GradScaler(enabled=USE_AMP and DEVICE == "cuda")

print(f"Fine-tune Teacher: {TEACHER_FT_EPOCHS} epochs | batch_size={BATCH_SIZE_TEACHER_FT}")
teacher_model.train()
for epoch in range(TEACHER_FT_EPOCHS):
    epoch_losses = []
    for start in range(0, len(fashion_train), BATCH_SIZE_TEACHER_FT):
        batch = fashion_train[start:start + BATCH_SIZE_TEACHER_FT]
        if not batch:
            continue
        pil_imgs = [Image.open(b["image_path"]).convert("RGB") for b in batch]
        gt_caps  = [b["caption"] for b in batch]
        gt_enc = SHARED_PROCESSOR(images=pil_imgs, text=gt_caps, return_tensors="pt",
                                   padding="max_length", max_length=MAX_LEN, truncation=True).to(DEVICE)
        gt_labels = make_labels(gt_enc["input_ids"])

        optimizer_teacher.zero_grad()
        with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=USE_AMP and DEVICE == "cuda"):
            out = teacher_model(pixel_values=gt_enc["pixel_values"], input_ids=gt_enc["input_ids"],
                                 attention_mask=gt_enc["attention_mask"], labels=gt_labels)
            loss = out.loss
        scaler_teacher.scale(loss).backward()
        scaler_teacher.unscale_(optimizer_teacher)
        torch.nn.utils.clip_grad_norm_(trainable_teacher_params, 1.0)
        scaler_teacher.step(optimizer_teacher)
        scaler_teacher.update()
        scheduler_teacher.step()
        epoch_losses.append(loss.item())
    print(f"[Teacher FT] Epoch {epoch+1}/{TEACHER_FT_EPOCHS} | loss={sum(epoch_losses)/len(epoch_losses):.4f}")

try:
    teacher_model.gradient_checkpointing_disable()
except Exception:
    pass
teacher_model = teacher_model.half().eval()
for p in teacher_model.parameters():
    p.requires_grad = False

free_gpu('optimizer_teacher', 'scheduler_teacher', 'scaler_teacher')

print("--- Đánh giá Teacher (fine-tuned) trên VAL SET ---")
teach_ft_bleu, teach_ft_rouge, teach_ft_cider = evaluate_model(teacher_model, fashion_val, is_teacher=True)
results["Teacher (fine-tuned)"] = (teach_ft_bleu, teach_ft_rouge, teach_ft_cider)
print(f"Teacher (fine-tuned): BLEU={teach_ft_bleu:.4f} ROUGE-L={teach_ft_rouge:.4f} CIDEr={teach_ft_cider:.4f}")

# =====================================================================
# PHẦN 4 — NO-KD BASELINE
# =====================================================================
student_model_nokd = BlipForConditionalGeneration.from_pretrained(
    "Salesforce/blip-image-captioning-base"
).to(DEVICE)
optimizer_nokd = AdamW(student_model_nokd.parameters(), lr=LR, weight_decay=0.01)
scheduler_nokd = get_linear_schedule_with_warmup(
    optimizer_nokd, num_warmup_steps=warmup_steps, num_training_steps=total_steps
)
scaler_nokd = torch.cuda.amp.GradScaler(enabled=USE_AMP and DEVICE == "cuda")

print("Training No-KD baseline...")
for epoch in range(NUM_EPOCHS):
    student_model_nokd.train()
    epoch_losses = []
    for start in range(0, len(fashion_train), BATCH_SIZE):
        batch = fashion_train[start:start + BATCH_SIZE]
        if not batch:
            continue
        pil_imgs = [Image.open(b["image_path"]).convert("RGB") for b in batch]
        gt_caps  = [b["caption"] for b in batch]
        gt_enc = SHARED_PROCESSOR(images=pil_imgs, text=gt_caps, return_tensors="pt",
                                   padding="max_length", max_length=MAX_LEN, truncation=True).to(DEVICE)
        gt_labels = make_labels(gt_enc["input_ids"])

        optimizer_nokd.zero_grad()
        with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=USE_AMP and DEVICE == "cuda"):
            out = student_model_nokd(pixel_values=gt_enc["pixel_values"], input_ids=gt_enc["input_ids"],
                                      attention_mask=gt_enc["attention_mask"], labels=gt_labels)
            loss = out.loss
        scaler_nokd.scale(loss).backward()
        scaler_nokd.unscale_(optimizer_nokd)
        torch.nn.utils.clip_grad_norm_(student_model_nokd.parameters(), 1.0)
        scaler_nokd.step(optimizer_nokd)
        scaler_nokd.update()
        scheduler_nokd.step()
        epoch_losses.append(loss.item())
    print(f"[No-KD] Epoch {epoch+1}/{NUM_EPOCHS} | loss={sum(epoch_losses)/len(epoch_losses):.4f}")

print("--- Đánh giá No-KD baseline trên VAL SET ---")
nokd_bleu, nokd_rouge, nokd_cider = evaluate_model(student_model_nokd, fashion_val)
results["No-KD (baseline)"] = (nokd_bleu, nokd_rouge, nokd_cider)
print(f"No-KD: BLEU={nokd_bleu:.4f} ROUGE-L={nokd_rouge:.4f} CIDEr={nokd_cider:.4f}")

free_gpu('student_model_nokd', 'optimizer_nokd', 'scheduler_nokd', 'scaler_nokd')

# =====================================================================
# PHẦN 5 — FEATURE-KD: FitNets (pooled feature + Adapter)
# =====================================================================
def get_pooled_image_feature(model, pixel_values):
    vision_out = model.vision_model(pixel_values=pixel_values)
    return vision_out.pooler_output


student_model_fitnets = BlipForConditionalGeneration.from_pretrained(
    "Salesforce/blip-image-captioning-base"
).to(DEVICE)
teacher_hidden = teacher_model.vision_model.config.hidden_size
student_hidden = student_model_fitnets.vision_model.config.hidden_size
adapter_fitnets = nn.Linear(student_hidden, teacher_hidden).to(DEVICE)

optimizer_fitnets = AdamW(
    list(student_model_fitnets.parameters()) + list(adapter_fitnets.parameters()),
    lr=LR, weight_decay=0.01
)
feat_steps = max(1, len(fashion_train) // BATCH_SIZE_FEAT) * NUM_EPOCHS
scheduler_fitnets = get_linear_schedule_with_warmup(
    optimizer_fitnets, num_warmup_steps=int(feat_steps * WARMUP_RATIO), num_training_steps=feat_steps
)
scaler_fitnets = torch.cuda.amp.GradScaler(enabled=USE_AMP and DEVICE == "cuda")

print(f"Training FitNets (batch_size={BATCH_SIZE_FEAT})...")
for epoch in range(NUM_EPOCHS):
    student_model_fitnets.train(); adapter_fitnets.train()
    epoch_losses = []
    for start in range(0, len(fashion_train), BATCH_SIZE_FEAT):
        batch = fashion_train[start:start + BATCH_SIZE_FEAT]
        if not batch:
            continue
        pil_imgs = [Image.open(b["image_path"]).convert("RGB") for b in batch]
        gt_caps  = [b["caption"] for b in batch]
        gt_enc = SHARED_PROCESSOR(images=pil_imgs, text=gt_caps, return_tensors="pt",
                                   padding="max_length", max_length=MAX_LEN, truncation=True).to(DEVICE)
        gt_labels = make_labels(gt_enc["input_ids"])

        with torch.no_grad():
            teacher_feat = get_pooled_image_feature(teacher_model, gt_enc["pixel_values"].half()).float()

        optimizer_fitnets.zero_grad()
        with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=USE_AMP and DEVICE == "cuda"):
            student_feat = get_pooled_image_feature(student_model_fitnets, gt_enc["pixel_values"])
            adapted_feat = adapter_fitnets(student_feat)
            loss_feature = F.mse_loss(adapted_feat.float(), teacher_feat)

            out_gt = student_model_fitnets(pixel_values=gt_enc["pixel_values"], input_ids=gt_enc["input_ids"],
                                            attention_mask=gt_enc["attention_mask"], labels=gt_labels)
            loss = (1 - ALPHA_FEAT) * out_gt.loss + ALPHA_FEAT * loss_feature

        scaler_fitnets.scale(loss).backward()
        scaler_fitnets.unscale_(optimizer_fitnets)
        torch.nn.utils.clip_grad_norm_(
            list(student_model_fitnets.parameters()) + list(adapter_fitnets.parameters()), 1.0
        )
        scaler_fitnets.step(optimizer_fitnets)
        scaler_fitnets.update()
        scheduler_fitnets.step()
        epoch_losses.append(loss.item())
    print(f"[FitNets] Epoch {epoch+1}/{NUM_EPOCHS} | loss={sum(epoch_losses)/len(epoch_losses):.4f} "
          f"(gt={out_gt.loss.item():.4f}, feat={loss_feature.item():.4f})")

print("--- Đánh giá FitNets trên VAL SET ---")
fitnets_bleu, fitnets_rouge, fitnets_cider = evaluate_model(student_model_fitnets, fashion_val)
results["FitNets (Student)"] = (fitnets_bleu, fitnets_rouge, fitnets_cider)
print(f"FitNets: BLEU={fitnets_bleu:.4f} ROUGE-L={fitnets_rouge:.4f} CIDEr={fitnets_cider:.4f}")

free_gpu('student_model_fitnets', 'adapter_fitnets', 'optimizer_fitnets', 'scheduler_fitnets', 'scaler_fitnets')

# =====================================================================
# PHẦN 6 — FEATURE-KD: ATTENTION TRANSFER (Zagoruyko & Komodakis, 2017)
# =====================================================================
# Khác FitNets: so sánh SPATIAL ATTENTION MAP (1 giá trị/patch, tổng bình
# phương activation theo chiều channel rồi chuẩn hoá L2) thay vì pooled
# feature -> map có shape [B, N_patches] KHÔNG phụ thuộc số channel, nên
# KHÔNG cần Adapter (BLIP-large/BLIP-base cùng patch grid vì dùng chung
# SHARED_PROCESSOR để resize ảnh).

def get_attention_map(hidden_states, eps=1e-6):
    """hidden_states: [B, N, C] (patch tokens, kể cả CLS) -> attention map [B, N]"""
    att = hidden_states.pow(2).sum(dim=-1)          # tổng bình phương theo channel
    att = F.normalize(att, p=2, dim=1, eps=eps)      # chuẩn hoá L2 theo chiều spatial
    return att


def get_last_hidden_states(model, pixel_values):
    vision_out = model.vision_model(pixel_values=pixel_values, output_hidden_states=True)
    return vision_out.hidden_states[-1]   # [B, N, C] của layer cuối


student_model_at = BlipForConditionalGeneration.from_pretrained(
    "Salesforce/blip-image-captioning-base"
).to(DEVICE)

optimizer_at = AdamW(student_model_at.parameters(), lr=LR, weight_decay=0.01)
scheduler_at = get_linear_schedule_with_warmup(
    optimizer_at, num_warmup_steps=int(feat_steps * WARMUP_RATIO), num_training_steps=feat_steps
)
scaler_at = torch.cuda.amp.GradScaler(enabled=USE_AMP and DEVICE == "cuda")

print(f"Training Attention Transfer (batch_size={BATCH_SIZE_FEAT})...")
for epoch in range(NUM_EPOCHS):
    student_model_at.train()
    epoch_losses = []
    for start in range(0, len(fashion_train), BATCH_SIZE_FEAT):
        batch = fashion_train[start:start + BATCH_SIZE_FEAT]
        if not batch:
            continue
        pil_imgs = [Image.open(b["image_path"]).convert("RGB") for b in batch]
        gt_caps  = [b["caption"] for b in batch]
        gt_enc = SHARED_PROCESSOR(images=pil_imgs, text=gt_caps, return_tensors="pt",
                                   padding="max_length", max_length=MAX_LEN, truncation=True).to(DEVICE)
        gt_labels = make_labels(gt_enc["input_ids"])

        with torch.no_grad():
            teacher_att = get_attention_map(
                get_last_hidden_states(teacher_model, gt_enc["pixel_values"].half()).float()
            )

        optimizer_at.zero_grad()
        with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=USE_AMP and DEVICE == "cuda"):
            student_hidden_states = get_last_hidden_states(student_model_at, gt_enc["pixel_values"])
            student_att = get_attention_map(student_hidden_states.float())
            loss_at = F.mse_loss(student_att, teacher_att)

            out_gt = student_model_at(pixel_values=gt_enc["pixel_values"], input_ids=gt_enc["input_ids"],
                                       attention_mask=gt_enc["attention_mask"], labels=gt_labels)
            loss = (1 - ALPHA_AT) * out_gt.loss + ALPHA_AT * loss_at

        scaler_at.scale(loss).backward()
        scaler_at.unscale_(optimizer_at)
        torch.nn.utils.clip_grad_norm_(student_model_at.parameters(), 1.0)
        scaler_at.step(optimizer_at)
        scaler_at.update()
        scheduler_at.step()
        epoch_losses.append(loss.item())
    print(f"[AT] Epoch {epoch+1}/{NUM_EPOCHS} | loss={sum(epoch_losses)/len(epoch_losses):.4f} "
          f"(gt={out_gt.loss.item():.4f}, at={loss_at.item():.4f})")

print("--- Đánh giá Attention Transfer trên VAL SET ---")
at_bleu, at_rouge, at_cider = evaluate_model(student_model_at, fashion_val)
results["Attention Transfer (Student)"] = (at_bleu, at_rouge, at_cider)
print(f"Attention Transfer: BLEU={at_bleu:.4f} ROUGE-L={at_rouge:.4f} CIDEr={at_cider:.4f}")

free_gpu('student_model_at', 'optimizer_at', 'scheduler_at', 'scaler_at')

# =====================================================================
# PHẦN 7 — BẢNG SO SÁNH
# =====================================================================
col_order = ["Teacher (zero-shot)", "Teacher (fine-tuned)", "No-KD (baseline)",
             "FitNets (Student)", "Attention Transfer (Student)"]
data = {"Metric": ["BLEU", "ROUGE-L", "CIDEr"]}
for col in col_order:
    b, r, c = results[col]
    data[col] = [b, r, c]
df_results = pd.DataFrame(data).round(4)
print("\nBẢNG KẾT QUẢ FILE 2 — FEATURE-BASED KD (VAL SET)")
display(df_results)

import matplotlib.pyplot as plt
import numpy as np
metrics = ['BLEU', 'ROUGE', 'CIDEr']
vals = [list(results[c]) for c in col_order]
colors = ['#999999', '#555555', '#B4B2A9', '#55A868', '#8172B2']
x = np.arange(len(metrics)); width = 0.15
fig, ax = plt.subplots(figsize=(12, 6))
for i, (v, c, lbl) in enumerate(zip(vals, colors, col_order)):
    ax.bar(x + (i - 2) * width, v, width, label=lbl, color=c)
ax.set_ylabel('Scores'); ax.set_xticks(x); ax.set_xticklabels(metrics)
ax.set_title('File 2 — Feature-based KD (FitNets, Attention Transfer) vs No-KD (Fashion200k, val set)')
ax.legend(); fig.tight_layout(); plt.show()

with open("results_file2.json", "w") as f:
    json.dump({k: list(v) for k, v in results.items()}, f, indent=2)
print("Đã lưu results_file2.json")

print("Đang tải lại các model Student để hiển thị...")

# Tải lại các model (lưu ý: đây là trọng số base ban đầu)
if 'student_model_nokd' not in globals() or student_model_nokd is None:
    student_model_nokd = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base").to(DEVICE)

if 'student_model_fitnets' not in globals() or student_model_fitnets is None:
    student_model_fitnets = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base").to(DEVICE)

if 'student_model_at' not in globals() or student_model_at is None:
    student_model_at = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base").to(DEVICE)

# Cập nhật lại dictionary hiển thị
models_to_show = {
    "Teacher (FT)": teacher_model if 'teacher_model' in globals() else None,
    "No-KD (Base/Reloaded)": student_model_nokd,
    "FitNets (Base/Reloaded)": student_model_fitnets,
    "Attention Transfer (Base/Reloaded)": student_model_at
}

print("--- Đã tải xong. Đang chạy lại visualization --- ")
visualize_predictions(fashion_val, models_to_show, SHARED_PROCESSOR, DEVICE)